// Code generated by lungo 1.81.24 from Lean 4.34.1 for program capdagFormal; DO NOT EDIT.

// Package formal calls the Lean program capdagFormal (generated by lungo).
package formal

/*
#cgo CFLAGS: -I${SRCDIR}
#include <stdlib.h>
#include "capdagFormal_program.h"

static int32_t capdagFormal_go_call(lungo_entry f, const uint8_t *in, size_t n, lungo_buffer *out) { return f(in, n, out); }
*/
import "C"

import (
	"math/big"
	"sync"
	"unsafe"

	lungo "github.com/machinefabric/lungo-go"
	formal "github.com/machinefabric/tagged-urn-go/formal"
)

// Generated for exactly this version of the support module.
const _ = lungo.EnforceVersion1_81_24

var programOnce sync.Once
var theProgram *lungo.Program

func program() *lungo.Program {
	programOnce.Do(func() { theProgram = lungo.NewProgram(unsafe.Pointer(C.capdagFormal__types())) })
	return theProgram
}

func call(entry C.lungo_entry, in []byte) (int32, []byte) {
	var buf C.lungo_buffer
	var p *C.uint8_t
	if len(in) > 0 {
		p = (*C.uint8_t)(unsafe.Pointer(&in[0]))
	}
	status := C.capdagFormal_go_call(entry, p, C.size_t(len(in)), &buf)
	var out []byte
	if buf.len > 0 {
		out = C.GoBytes(unsafe.Pointer(buf.data), C.int(buf.len))
	}
	C.lungo_buffer_free(&buf)
	return int32(status), out
}

// The packages providing this program's extern types were generated for the layouts it was.
func init() {
	if formal.WfFingerprint != "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785" {
		panic("TaggedUrn.Exec.Wf of github.com/machinefabric/tagged-urn-go/formal has another layout than the one this program was generated for: regenerate both from the same Lean definition")
	}
}

// WfCap is Lean's CapDAG.Exec.WfCap.
type WfCap struct {
	Input  formal.Wf
	Output formal.Wf
	Other  formal.Wf
	Effect Effect
}

// WfCapFingerprint is the layout fingerprint of Lean's CapDAG.Exec.WfCap: a package using WfCap from this one checks it.
const WfCapFingerprint = "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830"

type wfCapDescriptor struct{}

// WfCapType describes CapDAG.Exec.WfCap for polymorphic functions.
func WfCapType() lungo.Type[WfCap] {
	return wfCapDescriptor{}
}

func (t wfCapDescriptor) Expr() []byte { return lungo.InductiveExpr(0) }

func (t wfCapDescriptor) Encode(w *lungo.Writer, v WfCap) error {
	w.U32(0)
	if err := extWfType().Encode(w, v.Input); err != nil {
		return err
	}
	if err := extWfType().Encode(w, v.Output); err != nil {
		return err
	}
	if err := extWfType().Encode(w, v.Other); err != nil {
		return err
	}
	if err := EffectType().Encode(w, v.Effect); err != nil {
		return err
	}
	return nil
}

func (t wfCapDescriptor) Decode(r *lungo.Reader) (WfCap, error) {
	var v WfCap
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Exec.WfCap", c)
	}
	f0, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Input = f0
	f1, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Output = f1
	f2, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Other = f2
	f3, err := EffectType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Effect = f3
	return v, nil
}

// Effect is Lean's CapDAG.Effect: one of EffectUnspecified, EffectDeclared, EffectNone, EffectPatch.
type Effect interface{ isEffect() }

// EffectUnspecified is Lean's CapDAG.Effect.unspecified.
type EffectUnspecified struct{}

func (EffectUnspecified) isEffect() {}

// EffectDeclared is Lean's CapDAG.Effect.declared.
type EffectDeclared struct{}

func (EffectDeclared) isEffect() {}

// EffectNone is Lean's CapDAG.Effect.none.
type EffectNone struct{}

func (EffectNone) isEffect() {}

// EffectPatch is Lean's CapDAG.Effect.patch.
type EffectPatch struct{}

func (EffectPatch) isEffect() {}

// EffectFingerprint is the layout fingerprint of Lean's CapDAG.Effect: a package using Effect from this one checks it.
const EffectFingerprint = "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477"

type effectDescriptor struct{}

// EffectType describes CapDAG.Effect for polymorphic functions.
func EffectType() lungo.Type[Effect] {
	return effectDescriptor{}
}

func (t effectDescriptor) Expr() []byte { return lungo.InductiveExpr(1) }

func (t effectDescriptor) Encode(w *lungo.Writer, v Effect) error {
	switch x := v.(type) {
	case EffectUnspecified:
		w.U32(0)
		return nil
	case *EffectUnspecified:
		if x == nil {
			return lungo.Malformed("a nil *EffectUnspecified")
		}
		return t.Encode(w, *x)
	case EffectDeclared:
		w.U32(1)
		return nil
	case *EffectDeclared:
		if x == nil {
			return lungo.Malformed("a nil *EffectDeclared")
		}
		return t.Encode(w, *x)
	case EffectNone:
		w.U32(2)
		return nil
	case *EffectNone:
		if x == nil {
			return lungo.Malformed("a nil *EffectNone")
		}
		return t.Encode(w, *x)
	case EffectPatch:
		w.U32(3)
		return nil
	case *EffectPatch:
		if x == nil {
			return lungo.Malformed("a nil *EffectPatch")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Effect")
}

func (t effectDescriptor) Decode(r *lungo.Reader) (Effect, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v EffectUnspecified
		return v, nil
	case 1:
		var v EffectDeclared
		return v, nil
	case 2:
		var v EffectNone
		return v, nil
	case 3:
		var v EffectPatch
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Effect", c)
}

// WfQuery is Lean's CapDAG.Exec.WfQuery.
type WfQuery struct {
	Input  WfAsk
	Output WfAsk
	Tags   formal.Wf
	Effect Effect
}

// WfQueryFingerprint is the layout fingerprint of Lean's CapDAG.Exec.WfQuery: a package using WfQuery from this one checks it.
const WfQueryFingerprint = "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e"

type wfQueryDescriptor struct{}

// WfQueryType describes CapDAG.Exec.WfQuery for polymorphic functions.
func WfQueryType() lungo.Type[WfQuery] {
	return wfQueryDescriptor{}
}

func (t wfQueryDescriptor) Expr() []byte { return lungo.InductiveExpr(2) }

func (t wfQueryDescriptor) Encode(w *lungo.Writer, v WfQuery) error {
	w.U32(0)
	if err := WfAskType().Encode(w, v.Input); err != nil {
		return err
	}
	if err := WfAskType().Encode(w, v.Output); err != nil {
		return err
	}
	if err := extWfType().Encode(w, v.Tags); err != nil {
		return err
	}
	if err := EffectType().Encode(w, v.Effect); err != nil {
		return err
	}
	return nil
}

func (t wfQueryDescriptor) Decode(r *lungo.Reader) (WfQuery, error) {
	var v WfQuery
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Exec.WfQuery", c)
	}
	f0, err := WfAskType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Input = f0
	f1, err := WfAskType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Output = f1
	f2, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Tags = f2
	f3, err := EffectType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Effect = f3
	return v, nil
}

type extWfDescriptor struct{}

// extWfType describes Lean's TaggedUrn.Exec.Wf, provided by github.com/machinefabric/tagged-urn-go/formal.
func extWfType() lungo.Type[formal.Wf] {
	return extWfDescriptor{}
}

func (t extWfDescriptor) Expr() []byte { return lungo.InductiveExpr(3) }
func (t extWfDescriptor) Encode(w *lungo.Writer, v formal.Wf) error {
	return formal.WfType().Encode(w, v)
}
func (t extWfDescriptor) Decode(r *lungo.Reader) (formal.Wf, error) {
	return formal.WfType().Decode(r)
}

// Grade is Lean's CapDAG.Grade: one of GradeExact, GradeGuaranteed, GradePossible, GradeNone.
type Grade interface{ isGrade() }

// GradeExact is Lean's CapDAG.Grade.exact.
type GradeExact struct{}

func (GradeExact) isGrade() {}

// GradeGuaranteed is Lean's CapDAG.Grade.guaranteed.
type GradeGuaranteed struct{}

func (GradeGuaranteed) isGrade() {}

// GradePossible is Lean's CapDAG.Grade.possible.
type GradePossible struct{}

func (GradePossible) isGrade() {}

// GradeNone is Lean's CapDAG.Grade.none.
type GradeNone struct{}

func (GradeNone) isGrade() {}

// GradeFingerprint is the layout fingerprint of Lean's CapDAG.Grade: a package using Grade from this one checks it.
const GradeFingerprint = "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2"

type gradeDescriptor struct{}

// GradeType describes CapDAG.Grade for polymorphic functions.
func GradeType() lungo.Type[Grade] {
	return gradeDescriptor{}
}

func (t gradeDescriptor) Expr() []byte { return lungo.InductiveExpr(4) }

func (t gradeDescriptor) Encode(w *lungo.Writer, v Grade) error {
	switch x := v.(type) {
	case GradeExact:
		w.U32(0)
		return nil
	case *GradeExact:
		if x == nil {
			return lungo.Malformed("a nil *GradeExact")
		}
		return t.Encode(w, *x)
	case GradeGuaranteed:
		w.U32(1)
		return nil
	case *GradeGuaranteed:
		if x == nil {
			return lungo.Malformed("a nil *GradeGuaranteed")
		}
		return t.Encode(w, *x)
	case GradePossible:
		w.U32(2)
		return nil
	case *GradePossible:
		if x == nil {
			return lungo.Malformed("a nil *GradePossible")
		}
		return t.Encode(w, *x)
	case GradeNone:
		w.U32(3)
		return nil
	case *GradeNone:
		if x == nil {
			return lungo.Malformed("a nil *GradeNone")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Grade")
}

func (t gradeDescriptor) Decode(r *lungo.Reader) (Grade, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v GradeExact
		return v, nil
	case 1:
		var v GradeGuaranteed
		return v, nil
	case 2:
		var v GradePossible
		return v, nil
	case 3:
		var v GradeNone
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Grade", c)
}

// Constraint is Lean's TaggedUrn.Constraint: one of ConstraintMissing, ConstraintUnconstrained, ConstraintOptionalNot, ConstraintPresent, ConstraintPresentNot, ConstraintExact, ConstraintAbsent.
type Constraint interface{ isConstraint() }

// ConstraintMissing is Lean's TaggedUrn.Constraint.missing.
type ConstraintMissing struct{}

func (ConstraintMissing) isConstraint() {}

// ConstraintUnconstrained is Lean's TaggedUrn.Constraint.unconstrained.
type ConstraintUnconstrained struct{}

func (ConstraintUnconstrained) isConstraint() {}

// ConstraintOptionalNot is Lean's TaggedUrn.Constraint.optionalNot.
type ConstraintOptionalNot struct {
	Value string
}

func (ConstraintOptionalNot) isConstraint() {}

// ConstraintPresent is Lean's TaggedUrn.Constraint.present.
type ConstraintPresent struct{}

func (ConstraintPresent) isConstraint() {}

// ConstraintPresentNot is Lean's TaggedUrn.Constraint.presentNot.
type ConstraintPresentNot struct {
	Value string
}

func (ConstraintPresentNot) isConstraint() {}

// ConstraintExact is Lean's TaggedUrn.Constraint.exact.
type ConstraintExact struct {
	Value string
}

func (ConstraintExact) isConstraint() {}

// ConstraintAbsent is Lean's TaggedUrn.Constraint.absent.
type ConstraintAbsent struct{}

func (ConstraintAbsent) isConstraint() {}

// ConstraintFingerprint is the layout fingerprint of Lean's TaggedUrn.Constraint: a package using Constraint from this one checks it.
const ConstraintFingerprint = "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"

type constraintDescriptor struct{}

// ConstraintType describes TaggedUrn.Constraint for polymorphic functions.
func ConstraintType() lungo.Type[Constraint] {
	return constraintDescriptor{}
}

func (t constraintDescriptor) Expr() []byte { return lungo.InductiveExpr(5) }

func (t constraintDescriptor) Encode(w *lungo.Writer, v Constraint) error {
	switch x := v.(type) {
	case ConstraintMissing:
		w.U32(0)
		return nil
	case *ConstraintMissing:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintMissing")
		}
		return t.Encode(w, *x)
	case ConstraintUnconstrained:
		w.U32(1)
		return nil
	case *ConstraintUnconstrained:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintUnconstrained")
		}
		return t.Encode(w, *x)
	case ConstraintOptionalNot:
		w.U32(2)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintOptionalNot:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintOptionalNot")
		}
		return t.Encode(w, *x)
	case ConstraintPresent:
		w.U32(3)
		return nil
	case *ConstraintPresent:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintPresent")
		}
		return t.Encode(w, *x)
	case ConstraintPresentNot:
		w.U32(4)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintPresentNot:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintPresentNot")
		}
		return t.Encode(w, *x)
	case ConstraintExact:
		w.U32(5)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintExact:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintExact")
		}
		return t.Encode(w, *x)
	case ConstraintAbsent:
		w.U32(6)
		return nil
	case *ConstraintAbsent:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintAbsent")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Constraint")
}

func (t constraintDescriptor) Decode(r *lungo.Reader) (Constraint, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v ConstraintMissing
		return v, nil
	case 1:
		var v ConstraintUnconstrained
		return v, nil
	case 2:
		var v ConstraintOptionalNot
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 3:
		var v ConstraintPresent
		return v, nil
	case 4:
		var v ConstraintPresentNot
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 5:
		var v ConstraintExact
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 6:
		var v ConstraintAbsent
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of TaggedUrn.Constraint", c)
}

// WfAsk is Lean's CapDAG.Exec.WfAsk: one of WfAskUnknown, WfAskWithin, WfAskCovers, WfAskSame.
type WfAsk interface{ isWfAsk() }

// WfAskUnknown is Lean's CapDAG.Exec.WfAsk.unknown.
type WfAskUnknown struct{}

func (WfAskUnknown) isWfAsk() {}

// WfAskWithin is Lean's CapDAG.Exec.WfAsk.within.
type WfAskWithin struct {
	U formal.Wf
}

func (WfAskWithin) isWfAsk() {}

// WfAskCovers is Lean's CapDAG.Exec.WfAsk.covers.
type WfAskCovers struct {
	U formal.Wf
}

func (WfAskCovers) isWfAsk() {}

// WfAskSame is Lean's CapDAG.Exec.WfAsk.same.
type WfAskSame struct {
	U formal.Wf
}

func (WfAskSame) isWfAsk() {}

// WfAskFingerprint is the layout fingerprint of Lean's CapDAG.Exec.WfAsk: a package using WfAsk from this one checks it.
const WfAskFingerprint = "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952"

type wfAskDescriptor struct{}

// WfAskType describes CapDAG.Exec.WfAsk for polymorphic functions.
func WfAskType() lungo.Type[WfAsk] {
	return wfAskDescriptor{}
}

func (t wfAskDescriptor) Expr() []byte { return lungo.InductiveExpr(6) }

func (t wfAskDescriptor) Encode(w *lungo.Writer, v WfAsk) error {
	switch x := v.(type) {
	case WfAskUnknown:
		w.U32(0)
		return nil
	case *WfAskUnknown:
		if x == nil {
			return lungo.Malformed("a nil *WfAskUnknown")
		}
		return t.Encode(w, *x)
	case WfAskWithin:
		w.U32(1)
		if err := extWfType().Encode(w, x.U); err != nil {
			return err
		}
		return nil
	case *WfAskWithin:
		if x == nil {
			return lungo.Malformed("a nil *WfAskWithin")
		}
		return t.Encode(w, *x)
	case WfAskCovers:
		w.U32(2)
		if err := extWfType().Encode(w, x.U); err != nil {
			return err
		}
		return nil
	case *WfAskCovers:
		if x == nil {
			return lungo.Malformed("a nil *WfAskCovers")
		}
		return t.Encode(w, *x)
	case WfAskSame:
		w.U32(3)
		if err := extWfType().Encode(w, x.U); err != nil {
			return err
		}
		return nil
	case *WfAskSame:
		if x == nil {
			return lungo.Malformed("a nil *WfAskSame")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil WfAsk")
}

func (t wfAskDescriptor) Decode(r *lungo.Reader) (WfAsk, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v WfAskUnknown
		return v, nil
	case 1:
		var v WfAskWithin
		f0, err := extWfType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.U = f0
		return v, nil
	case 2:
		var v WfAskCovers
		f0, err := extWfType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.U = f0
		return v, nil
	case 3:
		var v WfAskSame
		f0, err := extWfType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.U = f0
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Exec.WfAsk", c)
}

// Accepts is Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Accepts(pattern WfCap, cap_ WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, pattern); err != nil {
		return
	}
	if err = WfCapType().Encode(w, cap_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_daccepts), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Comparable is Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Comparable(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dcomparable), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Dispatch is Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Dispatch(candidate WfCap, request WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, candidate); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_ddispatch), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// EffectOk is Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool
func EffectOk(candidate Effect, request Effect) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = EffectType().Encode(w, candidate); err != nil {
		return
	}
	if err = EffectType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_deffectOk), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Equivalent is Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Equivalent(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dequivalent), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Flows is Lean's CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Flows(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dflows), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// MayDispatch is Lean's CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func MayDispatch(candidate WfCap, request WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, candidate); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dmayDispatch), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// MayFlow is Lean's CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func MayFlow(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dmayFlow), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// QueryAdmits is Lean's CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool
func QueryAdmits(q WfQuery, c_ WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfQueryType().Encode(w, q); err != nil {
		return
	}
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryAdmits), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// QueryBetween is Lean's CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
func QueryBetween(input formal.Wf, output formal.Wf, tags formal.Wf) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = extWfType().Encode(w, input); err != nil {
		return
	}
	if err = extWfType().Encode(w, output); err != nil {
		return
	}
	if err = extWfType().Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryBetween), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// QueryConsuming is Lean's CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
func QueryConsuming(input formal.Wf, tags formal.Wf) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = extWfType().Encode(w, input); err != nil {
		return
	}
	if err = extWfType().Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryConsuming), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// QueryGrade is Lean's CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade
func QueryGrade(q WfQuery, c_ WfCap) (result Grade, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfQueryType().Encode(w, q); err != nil {
		return
	}
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryGrade), w.Bytes())
	return lungo.DecodeValue(program(), status, out, GradeType())
}

// QueryMayAdmit is Lean's CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool
func QueryMayAdmit(q WfQuery, c_ WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfQueryType().Encode(w, q); err != nil {
		return
	}
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryMayAdmit), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// QueryOfPattern is Lean's CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery
func QueryOfPattern(p_ WfCap) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, p_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryOfPattern), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// QueryOfRequest is Lean's CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery
func QueryOfRequest(r_ WfCap) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, r_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryOfRequest), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// QueryProducing is Lean's CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
func QueryProducing(output formal.Wf, tags formal.Wf) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = extWfType().Encode(w, output); err != nil {
		return
	}
	if err = extWfType().Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryProducing), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// RankingKey is Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat
func RankingKey(candidate WfCap, request WfCap) (result lungo.Pair[*big.Int, *big.Int], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, candidate); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_drankingKey), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.PairType(lungo.NatType, lungo.NatType))
}

// Select is Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap
func Select(candidates []WfCap, request WfCap) (result lungo.Option[WfCap], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.ListType(WfCapType()).Encode(w, candidates); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dselect), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(WfCapType()))
}

// Specificity is Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat
func Specificity(c_ WfCap) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dspecificity), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// Make is Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf
func Make(scheme string, tags []lungo.Pair[string, Constraint]) (result lungo.Option[formal.Wf], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.StringType.Encode(w, scheme); err != nil {
		return
	}
	if err = lungo.ListType(lungo.PairType(lungo.StringType, ConstraintType())).Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_TaggedUrn_dExec_dmake), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(extWfType()))
}
