// Code generated by lungo 1.87.0 from Lean 4.34.1 for program capdagFormal; DO NOT EDIT.

// Package formal calls the Lean program capdagFormal (generated by lungo).
package formal

/*
#cgo CFLAGS: -I${SRCDIR}
#include <stdlib.h>
#include "capdagFormal_program.h"

static int32_t capdagFormal_go_call(lungo_entry f, const uint8_t *in, size_t n, lungo_buffer *out) { return f(in, n, out); }
*/
import "C"

import (
	"math/big"
	"sync"
	"unsafe"

	lungo "github.com/machinefabric/lungo-go"
	formal "github.com/machinefabric/tagged-urn-go/formal"
)

// Generated for exactly this version of the support module.
const _ = lungo.EnforceVersion1_87_0

var programOnce sync.Once
var theProgram *lungo.Program

func program() *lungo.Program {
	programOnce.Do(func() { theProgram = lungo.NewProgram(unsafe.Pointer(C.capdagFormal__types())) })
	return theProgram
}

func call(entry C.lungo_entry, in []byte) (int32, []byte) {
	var buf C.lungo_buffer
	var p *C.uint8_t
	if len(in) > 0 {
		p = (*C.uint8_t)(unsafe.Pointer(&in[0]))
	}
	status := C.capdagFormal_go_call(entry, p, C.size_t(len(in)), &buf)
	var out []byte
	if buf.len > 0 {
		out = C.GoBytes(unsafe.Pointer(buf.data), C.int(buf.len))
	}
	C.lungo_buffer_free(&buf)
	return int32(status), out
}

// The packages providing this program's extern types were generated for the layouts it was.
func init() {
	if formal.WfFingerprint != "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785" {
		panic("TaggedUrn.Exec.Wf of github.com/machinefabric/tagged-urn-go/formal has another layout than the one this program was generated for: regenerate both from the same Lean definition")
	}
}

// Gate is Lean's CapDAG.Bifaci.Credit.Gate.
type Gate struct {
	Available *big.Int
	Closed    lungo.Option[string]
}

// GateFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Credit.Gate: a package using Gate from this one checks it.
const GateFingerprint = "b10dc9a4cff1977f4f6a2c415147f497f98740255d0158fb2b3a2a99d4d1b135"

type gateDescriptor struct{}

// GateType describes CapDAG.Bifaci.Credit.Gate for polymorphic functions.
func GateType() lungo.Type[Gate] {
	return gateDescriptor{}
}

func (t gateDescriptor) Expr() []byte { return lungo.InductiveExpr(0) }

func (t gateDescriptor) Encode(w *lungo.Writer, v Gate) error {
	w.U32(0)
	if err := lungo.NatType.Encode(w, v.Available); err != nil {
		return err
	}
	if err := lungo.OptionType(lungo.StringType).Encode(w, v.Closed); err != nil {
		return err
	}
	return nil
}

func (t gateDescriptor) Decode(r *lungo.Reader) (Gate, error) {
	var v Gate
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Credit.Gate", c)
	}
	f0, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Available = f0
	f1, err := lungo.OptionType(lungo.StringType).Decode(r)
	if err != nil {
		return v, err
	}
	v.Closed = f1
	return v, nil
}

// Acquire is Lean's CapDAG.Bifaci.Credit.Acquire: one of AcquireAcquired, AcquireWait, AcquireClosed.
type Acquire interface{ isAcquire() }

// AcquireAcquired is Lean's CapDAG.Bifaci.Credit.Acquire.acquired.
type AcquireAcquired struct {
	Gate Gate
}

func (AcquireAcquired) isAcquire() {}

// AcquireWait is Lean's CapDAG.Bifaci.Credit.Acquire.wait.
type AcquireWait struct{}

func (AcquireWait) isAcquire() {}

// AcquireClosed is Lean's CapDAG.Bifaci.Credit.Acquire.closed.
type AcquireClosed struct {
	Reason string
}

func (AcquireClosed) isAcquire() {}

// AcquireFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Credit.Acquire: a package using Acquire from this one checks it.
const AcquireFingerprint = "0dabbf62c4dad8c3f81811acc80f5c789d25191897bb2621de51b5f94e54a4c9"

type acquireDescriptor struct{}

// AcquireType describes CapDAG.Bifaci.Credit.Acquire for polymorphic functions.
func AcquireType() lungo.Type[Acquire] {
	return acquireDescriptor{}
}

func (t acquireDescriptor) Expr() []byte { return lungo.InductiveExpr(1) }

func (t acquireDescriptor) Encode(w *lungo.Writer, v Acquire) error {
	switch x := v.(type) {
	case AcquireAcquired:
		w.U32(0)
		if err := GateType().Encode(w, x.Gate); err != nil {
			return err
		}
		return nil
	case *AcquireAcquired:
		if x == nil {
			return lungo.Malformed("a nil *AcquireAcquired")
		}
		return t.Encode(w, *x)
	case AcquireWait:
		w.U32(1)
		return nil
	case *AcquireWait:
		if x == nil {
			return lungo.Malformed("a nil *AcquireWait")
		}
		return t.Encode(w, *x)
	case AcquireClosed:
		w.U32(2)
		if err := lungo.StringType.Encode(w, x.Reason); err != nil {
			return err
		}
		return nil
	case *AcquireClosed:
		if x == nil {
			return lungo.Malformed("a nil *AcquireClosed")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Acquire")
}

func (t acquireDescriptor) Decode(r *lungo.Reader) (Acquire, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v AcquireAcquired
		f0, err := GateType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.Gate = f0
		return v, nil
	case 1:
		var v AcquireWait
		return v, nil
	case 2:
		var v AcquireClosed
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Reason = f0
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Credit.Acquire", c)
}

// Window is Lean's CapDAG.Bifaci.Credit.Window.
type Window struct {
	Remaining *big.Int
	Pending   *big.Int
	Batch     *big.Int
}

// WindowFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Credit.Window: a package using Window from this one checks it.
const WindowFingerprint = "28df89763b22214ef57dfd7f1a3c0da786ff78af9768fe453cd451870749b6fe"

type windowDescriptor struct{}

// WindowType describes CapDAG.Bifaci.Credit.Window for polymorphic functions.
func WindowType() lungo.Type[Window] {
	return windowDescriptor{}
}

func (t windowDescriptor) Expr() []byte { return lungo.InductiveExpr(2) }

func (t windowDescriptor) Encode(w *lungo.Writer, v Window) error {
	w.U32(0)
	if err := lungo.NatType.Encode(w, v.Remaining); err != nil {
		return err
	}
	if err := lungo.NatType.Encode(w, v.Pending); err != nil {
		return err
	}
	if err := lungo.NatType.Encode(w, v.Batch); err != nil {
		return err
	}
	return nil
}

func (t windowDescriptor) Decode(r *lungo.Reader) (Window, error) {
	var v Window
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Credit.Window", c)
	}
	f0, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Remaining = f0
	f1, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Pending = f1
	f2, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Batch = f2
	return v, nil
}

// CreditArrival is Lean's CapDAG.Bifaci.Credit.Arrival: one of CreditArrivalAccepted, CreditArrivalViolation.
type CreditArrival interface{ isCreditArrival() }

// CreditArrivalAccepted is Lean's CapDAG.Bifaci.Credit.Arrival.accepted.
type CreditArrivalAccepted struct {
	Window Window
}

func (CreditArrivalAccepted) isCreditArrival() {}

// CreditArrivalViolation is Lean's CapDAG.Bifaci.Credit.Arrival.violation.
type CreditArrivalViolation struct{}

func (CreditArrivalViolation) isCreditArrival() {}

// CreditArrivalFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Credit.Arrival: a package using CreditArrival from this one checks it.
const CreditArrivalFingerprint = "940f01cf50eb8b763b9f44cc84753fcdbc65fbc0f816ab279408e74208649797"

type creditArrivalDescriptor struct{}

// CreditArrivalType describes CapDAG.Bifaci.Credit.Arrival for polymorphic functions.
func CreditArrivalType() lungo.Type[CreditArrival] {
	return creditArrivalDescriptor{}
}

func (t creditArrivalDescriptor) Expr() []byte { return lungo.InductiveExpr(3) }

func (t creditArrivalDescriptor) Encode(w *lungo.Writer, v CreditArrival) error {
	switch x := v.(type) {
	case CreditArrivalAccepted:
		w.U32(0)
		if err := WindowType().Encode(w, x.Window); err != nil {
			return err
		}
		return nil
	case *CreditArrivalAccepted:
		if x == nil {
			return lungo.Malformed("a nil *CreditArrivalAccepted")
		}
		return t.Encode(w, *x)
	case CreditArrivalViolation:
		w.U32(1)
		return nil
	case *CreditArrivalViolation:
		if x == nil {
			return lungo.Malformed("a nil *CreditArrivalViolation")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil CreditArrival")
}

func (t creditArrivalDescriptor) Decode(r *lungo.Reader) (CreditArrival, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v CreditArrivalAccepted
		f0, err := WindowType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.Window = f0
		return v, nil
	case 1:
		var v CreditArrivalViolation
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Credit.Arrival", c)
}

// Granted is Lean's CapDAG.Bifaci.Credit.Granted.
type Granted struct {
	Window Window
	Grant  *big.Int
}

// GrantedFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Credit.Granted: a package using Granted from this one checks it.
const GrantedFingerprint = "47f8d3e63e9aaf7c4b602f781afce57fc832e3d4d645c6adabd25c461abed233"

type grantedDescriptor struct{}

// GrantedType describes CapDAG.Bifaci.Credit.Granted for polymorphic functions.
func GrantedType() lungo.Type[Granted] {
	return grantedDescriptor{}
}

func (t grantedDescriptor) Expr() []byte { return lungo.InductiveExpr(4) }

func (t grantedDescriptor) Encode(w *lungo.Writer, v Granted) error {
	w.U32(0)
	if err := WindowType().Encode(w, v.Window); err != nil {
		return err
	}
	if err := lungo.NatType.Encode(w, v.Grant); err != nil {
		return err
	}
	return nil
}

func (t grantedDescriptor) Decode(r *lungo.Reader) (Granted, error) {
	var v Granted
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Credit.Granted", c)
	}
	f0, err := WindowType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Window = f0
	f1, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Grant = f1
	return v, nil
}

// FrameType is Lean's CapDAG.Bifaci.Flow.FrameType: one of FrameTypeHello, FrameTypeReq, FrameTypeChunk, FrameTypeFin, FrameTypeLog, FrameTypeErr, FrameTypeHeartbeat, FrameTypeStreamStart, FrameTypeStreamEnd, FrameTypeRelayNotify, FrameTypeRelayState, FrameTypeCancel, FrameTypeCredit, FrameTypeCloseStream.
type FrameType interface{ isFrameType() }

// FrameTypeHello is Lean's CapDAG.Bifaci.Flow.FrameType.hello.
type FrameTypeHello struct{}

func (FrameTypeHello) isFrameType() {}

// FrameTypeReq is Lean's CapDAG.Bifaci.Flow.FrameType.req.
type FrameTypeReq struct{}

func (FrameTypeReq) isFrameType() {}

// FrameTypeChunk is Lean's CapDAG.Bifaci.Flow.FrameType.chunk.
type FrameTypeChunk struct{}

func (FrameTypeChunk) isFrameType() {}

// FrameTypeFin is Lean's CapDAG.Bifaci.Flow.FrameType.fin.
type FrameTypeFin struct{}

func (FrameTypeFin) isFrameType() {}

// FrameTypeLog is Lean's CapDAG.Bifaci.Flow.FrameType.log.
type FrameTypeLog struct{}

func (FrameTypeLog) isFrameType() {}

// FrameTypeErr is Lean's CapDAG.Bifaci.Flow.FrameType.err.
type FrameTypeErr struct{}

func (FrameTypeErr) isFrameType() {}

// FrameTypeHeartbeat is Lean's CapDAG.Bifaci.Flow.FrameType.heartbeat.
type FrameTypeHeartbeat struct{}

func (FrameTypeHeartbeat) isFrameType() {}

// FrameTypeStreamStart is Lean's CapDAG.Bifaci.Flow.FrameType.streamStart.
type FrameTypeStreamStart struct{}

func (FrameTypeStreamStart) isFrameType() {}

// FrameTypeStreamEnd is Lean's CapDAG.Bifaci.Flow.FrameType.streamEnd.
type FrameTypeStreamEnd struct{}

func (FrameTypeStreamEnd) isFrameType() {}

// FrameTypeRelayNotify is Lean's CapDAG.Bifaci.Flow.FrameType.relayNotify.
type FrameTypeRelayNotify struct{}

func (FrameTypeRelayNotify) isFrameType() {}

// FrameTypeRelayState is Lean's CapDAG.Bifaci.Flow.FrameType.relayState.
type FrameTypeRelayState struct{}

func (FrameTypeRelayState) isFrameType() {}

// FrameTypeCancel is Lean's CapDAG.Bifaci.Flow.FrameType.cancel.
type FrameTypeCancel struct{}

func (FrameTypeCancel) isFrameType() {}

// FrameTypeCredit is Lean's CapDAG.Bifaci.Flow.FrameType.credit.
type FrameTypeCredit struct{}

func (FrameTypeCredit) isFrameType() {}

// FrameTypeCloseStream is Lean's CapDAG.Bifaci.Flow.FrameType.closeStream.
type FrameTypeCloseStream struct{}

func (FrameTypeCloseStream) isFrameType() {}

// FrameTypeFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Flow.FrameType: a package using FrameType from this one checks it.
const FrameTypeFingerprint = "3d6742b864aeb68cf6add586acfcd1a9663a3816d718f8d8aadc3c5e3dab3e2f"

type frameTypeDescriptor struct{}

// FrameTypeType describes CapDAG.Bifaci.Flow.FrameType for polymorphic functions.
func FrameTypeType() lungo.Type[FrameType] {
	return frameTypeDescriptor{}
}

func (t frameTypeDescriptor) Expr() []byte { return lungo.InductiveExpr(5) }

func (t frameTypeDescriptor) Encode(w *lungo.Writer, v FrameType) error {
	switch x := v.(type) {
	case FrameTypeHello:
		w.U32(0)
		return nil
	case *FrameTypeHello:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeHello")
		}
		return t.Encode(w, *x)
	case FrameTypeReq:
		w.U32(1)
		return nil
	case *FrameTypeReq:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeReq")
		}
		return t.Encode(w, *x)
	case FrameTypeChunk:
		w.U32(2)
		return nil
	case *FrameTypeChunk:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeChunk")
		}
		return t.Encode(w, *x)
	case FrameTypeFin:
		w.U32(3)
		return nil
	case *FrameTypeFin:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeFin")
		}
		return t.Encode(w, *x)
	case FrameTypeLog:
		w.U32(4)
		return nil
	case *FrameTypeLog:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeLog")
		}
		return t.Encode(w, *x)
	case FrameTypeErr:
		w.U32(5)
		return nil
	case *FrameTypeErr:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeErr")
		}
		return t.Encode(w, *x)
	case FrameTypeHeartbeat:
		w.U32(6)
		return nil
	case *FrameTypeHeartbeat:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeHeartbeat")
		}
		return t.Encode(w, *x)
	case FrameTypeStreamStart:
		w.U32(7)
		return nil
	case *FrameTypeStreamStart:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeStreamStart")
		}
		return t.Encode(w, *x)
	case FrameTypeStreamEnd:
		w.U32(8)
		return nil
	case *FrameTypeStreamEnd:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeStreamEnd")
		}
		return t.Encode(w, *x)
	case FrameTypeRelayNotify:
		w.U32(9)
		return nil
	case *FrameTypeRelayNotify:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeRelayNotify")
		}
		return t.Encode(w, *x)
	case FrameTypeRelayState:
		w.U32(10)
		return nil
	case *FrameTypeRelayState:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeRelayState")
		}
		return t.Encode(w, *x)
	case FrameTypeCancel:
		w.U32(11)
		return nil
	case *FrameTypeCancel:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeCancel")
		}
		return t.Encode(w, *x)
	case FrameTypeCredit:
		w.U32(12)
		return nil
	case *FrameTypeCredit:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeCredit")
		}
		return t.Encode(w, *x)
	case FrameTypeCloseStream:
		w.U32(13)
		return nil
	case *FrameTypeCloseStream:
		if x == nil {
			return lungo.Malformed("a nil *FrameTypeCloseStream")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil FrameType")
}

func (t frameTypeDescriptor) Decode(r *lungo.Reader) (FrameType, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v FrameTypeHello
		return v, nil
	case 1:
		var v FrameTypeReq
		return v, nil
	case 2:
		var v FrameTypeChunk
		return v, nil
	case 3:
		var v FrameTypeFin
		return v, nil
	case 4:
		var v FrameTypeLog
		return v, nil
	case 5:
		var v FrameTypeErr
		return v, nil
	case 6:
		var v FrameTypeHeartbeat
		return v, nil
	case 7:
		var v FrameTypeStreamStart
		return v, nil
	case 8:
		var v FrameTypeStreamEnd
		return v, nil
	case 9:
		var v FrameTypeRelayNotify
		return v, nil
	case 10:
		var v FrameTypeRelayState
		return v, nil
	case 11:
		var v FrameTypeCancel
		return v, nil
	case 12:
		var v FrameTypeCredit
		return v, nil
	case 13:
		var v FrameTypeCloseStream
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Flow.FrameType", c)
}

// Reorder is Lean's CapDAG.Bifaci.Flow.Reorder.
type Reorder struct {
	Expected *big.Int
	Held     []*big.Int
}

// ReorderFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Flow.Reorder: a package using Reorder from this one checks it.
const ReorderFingerprint = "d1e8b655f24db5e8b2348d6d41084a5c454346eb0a81fcf11b671432e72291bf"

type reorderDescriptor struct{}

// ReorderType describes CapDAG.Bifaci.Flow.Reorder for polymorphic functions.
func ReorderType() lungo.Type[Reorder] {
	return reorderDescriptor{}
}

func (t reorderDescriptor) Expr() []byte { return lungo.InductiveExpr(6) }

func (t reorderDescriptor) Encode(w *lungo.Writer, v Reorder) error {
	w.U32(0)
	if err := lungo.NatType.Encode(w, v.Expected); err != nil {
		return err
	}
	if err := lungo.ListType(lungo.NatType).Encode(w, v.Held); err != nil {
		return err
	}
	return nil
}

func (t reorderDescriptor) Decode(r *lungo.Reader) (Reorder, error) {
	var v Reorder
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Flow.Reorder", c)
	}
	f0, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Expected = f0
	f1, err := lungo.ListType(lungo.NatType).Decode(r)
	if err != nil {
		return v, err
	}
	v.Held = f1
	return v, nil
}

// Accepted is Lean's CapDAG.Bifaci.Flow.Accepted: one of AcceptedDeliver, AcceptedHold, AcceptedStale, AcceptedDuplicate, AcceptedOverflow.
type Accepted interface{ isAccepted() }

// AcceptedDeliver is Lean's CapDAG.Bifaci.Flow.Accepted.deliver.
type AcceptedDeliver struct {
	Flow Reorder
	Seqs []*big.Int
}

func (AcceptedDeliver) isAccepted() {}

// AcceptedHold is Lean's CapDAG.Bifaci.Flow.Accepted.hold.
type AcceptedHold struct {
	Flow Reorder
}

func (AcceptedHold) isAccepted() {}

// AcceptedStale is Lean's CapDAG.Bifaci.Flow.Accepted.stale.
type AcceptedStale struct{}

func (AcceptedStale) isAccepted() {}

// AcceptedDuplicate is Lean's CapDAG.Bifaci.Flow.Accepted.duplicate.
type AcceptedDuplicate struct{}

func (AcceptedDuplicate) isAccepted() {}

// AcceptedOverflow is Lean's CapDAG.Bifaci.Flow.Accepted.overflow.
type AcceptedOverflow struct{}

func (AcceptedOverflow) isAccepted() {}

// AcceptedFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Flow.Accepted: a package using Accepted from this one checks it.
const AcceptedFingerprint = "a821d7a044f52a71dfd932fff60d2f3560ce5197658283853a56fb54aa96b69b"

type acceptedDescriptor struct{}

// AcceptedType describes CapDAG.Bifaci.Flow.Accepted for polymorphic functions.
func AcceptedType() lungo.Type[Accepted] {
	return acceptedDescriptor{}
}

func (t acceptedDescriptor) Expr() []byte { return lungo.InductiveExpr(7) }

func (t acceptedDescriptor) Encode(w *lungo.Writer, v Accepted) error {
	switch x := v.(type) {
	case AcceptedDeliver:
		w.U32(0)
		if err := ReorderType().Encode(w, x.Flow); err != nil {
			return err
		}
		if err := lungo.ListType(lungo.NatType).Encode(w, x.Seqs); err != nil {
			return err
		}
		return nil
	case *AcceptedDeliver:
		if x == nil {
			return lungo.Malformed("a nil *AcceptedDeliver")
		}
		return t.Encode(w, *x)
	case AcceptedHold:
		w.U32(1)
		if err := ReorderType().Encode(w, x.Flow); err != nil {
			return err
		}
		return nil
	case *AcceptedHold:
		if x == nil {
			return lungo.Malformed("a nil *AcceptedHold")
		}
		return t.Encode(w, *x)
	case AcceptedStale:
		w.U32(2)
		return nil
	case *AcceptedStale:
		if x == nil {
			return lungo.Malformed("a nil *AcceptedStale")
		}
		return t.Encode(w, *x)
	case AcceptedDuplicate:
		w.U32(3)
		return nil
	case *AcceptedDuplicate:
		if x == nil {
			return lungo.Malformed("a nil *AcceptedDuplicate")
		}
		return t.Encode(w, *x)
	case AcceptedOverflow:
		w.U32(4)
		return nil
	case *AcceptedOverflow:
		if x == nil {
			return lungo.Malformed("a nil *AcceptedOverflow")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Accepted")
}

func (t acceptedDescriptor) Decode(r *lungo.Reader) (Accepted, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v AcceptedDeliver
		f0, err := ReorderType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.Flow = f0
		f1, err := lungo.ListType(lungo.NatType).Decode(r)
		if err != nil {
			return nil, err
		}
		v.Seqs = f1
		return v, nil
	case 1:
		var v AcceptedHold
		f0, err := ReorderType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.Flow = f0
		return v, nil
	case 2:
		var v AcceptedStale
		return v, nil
	case 3:
		var v AcceptedDuplicate
		return v, nil
	case 4:
		var v AcceptedOverflow
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Flow.Accepted", c)
}

// State is Lean's CapDAG.Bifaci.Pools.State.
type State struct {
	Pools []Pool
	Queue []Waiter
	Next  *big.Int
}

// StateFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Pools.State: a package using State from this one checks it.
const StateFingerprint = "20f7299c188d09234cda39e9cc356242e2b5bc56a09cf819d12d7f50fa24989b"

type stateDescriptor struct{}

// StateType describes CapDAG.Bifaci.Pools.State for polymorphic functions.
func StateType() lungo.Type[State] {
	return stateDescriptor{}
}

func (t stateDescriptor) Expr() []byte { return lungo.InductiveExpr(8) }

func (t stateDescriptor) Encode(w *lungo.Writer, v State) error {
	w.U32(0)
	if err := lungo.ListType(PoolType()).Encode(w, v.Pools); err != nil {
		return err
	}
	if err := lungo.ListType(WaiterType()).Encode(w, v.Queue); err != nil {
		return err
	}
	if err := lungo.NatType.Encode(w, v.Next); err != nil {
		return err
	}
	return nil
}

func (t stateDescriptor) Decode(r *lungo.Reader) (State, error) {
	var v State
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Pools.State", c)
	}
	f0, err := lungo.ListType(PoolType()).Decode(r)
	if err != nil {
		return v, err
	}
	v.Pools = f0
	f1, err := lungo.ListType(WaiterType()).Decode(r)
	if err != nil {
		return v, err
	}
	v.Queue = f1
	f2, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Next = f2
	return v, nil
}

// Waiter is Lean's CapDAG.Bifaci.Pools.Waiter.
type Waiter struct {
	Ticket *big.Int
	Chain  []string
}

// WaiterFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Pools.Waiter: a package using Waiter from this one checks it.
const WaiterFingerprint = "48d81c7e41df114e88751bb5c1f4a84c16bac3ad28d8eacba141d45f92c79da0"

type waiterDescriptor struct{}

// WaiterType describes CapDAG.Bifaci.Pools.Waiter for polymorphic functions.
func WaiterType() lungo.Type[Waiter] {
	return waiterDescriptor{}
}

func (t waiterDescriptor) Expr() []byte { return lungo.InductiveExpr(9) }

func (t waiterDescriptor) Encode(w *lungo.Writer, v Waiter) error {
	w.U32(0)
	if err := lungo.NatType.Encode(w, v.Ticket); err != nil {
		return err
	}
	if err := lungo.ListType(lungo.StringType).Encode(w, v.Chain); err != nil {
		return err
	}
	return nil
}

func (t waiterDescriptor) Decode(r *lungo.Reader) (Waiter, error) {
	var v Waiter
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Pools.Waiter", c)
	}
	f0, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Ticket = f0
	f1, err := lungo.ListType(lungo.StringType).Decode(r)
	if err != nil {
		return v, err
	}
	v.Chain = f1
	return v, nil
}

// PoolsArrival is Lean's CapDAG.Bifaci.Pools.Arrival: one of PoolsArrivalAdmitted, PoolsArrivalQueued, PoolsArrivalUnknownPool.
type PoolsArrival interface{ isPoolsArrival() }

// PoolsArrivalAdmitted is Lean's CapDAG.Bifaci.Pools.Arrival.admitted.
type PoolsArrivalAdmitted struct {
	State State
}

func (PoolsArrivalAdmitted) isPoolsArrival() {}

// PoolsArrivalQueued is Lean's CapDAG.Bifaci.Pools.Arrival.queued.
type PoolsArrivalQueued struct {
	State    State
	Ticket   *big.Int
	Position *big.Int
}

func (PoolsArrivalQueued) isPoolsArrival() {}

// PoolsArrivalUnknownPool is Lean's CapDAG.Bifaci.Pools.Arrival.unknownPool.
type PoolsArrivalUnknownPool struct {
	Name string
}

func (PoolsArrivalUnknownPool) isPoolsArrival() {}

// PoolsArrivalFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Pools.Arrival: a package using PoolsArrival from this one checks it.
const PoolsArrivalFingerprint = "6bee196c56c330c4ef348f4dd5a68558b2d19105592969cc64a0e7150bd22451"

type poolsArrivalDescriptor struct{}

// PoolsArrivalType describes CapDAG.Bifaci.Pools.Arrival for polymorphic functions.
func PoolsArrivalType() lungo.Type[PoolsArrival] {
	return poolsArrivalDescriptor{}
}

func (t poolsArrivalDescriptor) Expr() []byte { return lungo.InductiveExpr(10) }

func (t poolsArrivalDescriptor) Encode(w *lungo.Writer, v PoolsArrival) error {
	switch x := v.(type) {
	case PoolsArrivalAdmitted:
		w.U32(0)
		if err := StateType().Encode(w, x.State); err != nil {
			return err
		}
		return nil
	case *PoolsArrivalAdmitted:
		if x == nil {
			return lungo.Malformed("a nil *PoolsArrivalAdmitted")
		}
		return t.Encode(w, *x)
	case PoolsArrivalQueued:
		w.U32(1)
		if err := StateType().Encode(w, x.State); err != nil {
			return err
		}
		if err := lungo.NatType.Encode(w, x.Ticket); err != nil {
			return err
		}
		if err := lungo.NatType.Encode(w, x.Position); err != nil {
			return err
		}
		return nil
	case *PoolsArrivalQueued:
		if x == nil {
			return lungo.Malformed("a nil *PoolsArrivalQueued")
		}
		return t.Encode(w, *x)
	case PoolsArrivalUnknownPool:
		w.U32(2)
		if err := lungo.StringType.Encode(w, x.Name); err != nil {
			return err
		}
		return nil
	case *PoolsArrivalUnknownPool:
		if x == nil {
			return lungo.Malformed("a nil *PoolsArrivalUnknownPool")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil PoolsArrival")
}

func (t poolsArrivalDescriptor) Decode(r *lungo.Reader) (PoolsArrival, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v PoolsArrivalAdmitted
		f0, err := StateType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.State = f0
		return v, nil
	case 1:
		var v PoolsArrivalQueued
		f0, err := StateType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.State = f0
		f1, err := lungo.NatType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Ticket = f1
		f2, err := lungo.NatType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Position = f2
		return v, nil
	case 2:
		var v PoolsArrivalUnknownPool
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Name = f0
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Pools.Arrival", c)
}

// Patience is Lean's CapDAG.Bifaci.Pools.Patience: one of PatienceUnbounded, PatienceAtMost, PatienceExhausted.
type Patience interface{ isPatience() }

// PatienceUnbounded is Lean's CapDAG.Bifaci.Pools.Patience.unbounded.
type PatienceUnbounded struct{}

func (PatienceUnbounded) isPatience() {}

// PatienceAtMost is Lean's CapDAG.Bifaci.Pools.Patience.atMost.
type PatienceAtMost struct {
	Remaining *big.Int
}

func (PatienceAtMost) isPatience() {}

// PatienceExhausted is Lean's CapDAG.Bifaci.Pools.Patience.exhausted.
type PatienceExhausted struct{}

func (PatienceExhausted) isPatience() {}

// PatienceFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Pools.Patience: a package using Patience from this one checks it.
const PatienceFingerprint = "d32e3427e590ca6002e38cface52d020c7df74603f952bf568401f7291d5648c"

type patienceDescriptor struct{}

// PatienceType describes CapDAG.Bifaci.Pools.Patience for polymorphic functions.
func PatienceType() lungo.Type[Patience] {
	return patienceDescriptor{}
}

func (t patienceDescriptor) Expr() []byte { return lungo.InductiveExpr(11) }

func (t patienceDescriptor) Encode(w *lungo.Writer, v Patience) error {
	switch x := v.(type) {
	case PatienceUnbounded:
		w.U32(0)
		return nil
	case *PatienceUnbounded:
		if x == nil {
			return lungo.Malformed("a nil *PatienceUnbounded")
		}
		return t.Encode(w, *x)
	case PatienceAtMost:
		w.U32(1)
		if err := lungo.NatType.Encode(w, x.Remaining); err != nil {
			return err
		}
		return nil
	case *PatienceAtMost:
		if x == nil {
			return lungo.Malformed("a nil *PatienceAtMost")
		}
		return t.Encode(w, *x)
	case PatienceExhausted:
		w.U32(2)
		return nil
	case *PatienceExhausted:
		if x == nil {
			return lungo.Malformed("a nil *PatienceExhausted")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Patience")
}

func (t patienceDescriptor) Decode(r *lungo.Reader) (Patience, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v PatienceUnbounded
		return v, nil
	case 1:
		var v PatienceAtMost
		f0, err := lungo.NatType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Remaining = f0
		return v, nil
	case 2:
		var v PatienceExhausted
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Pools.Patience", c)
}

// Phase is Lean's CapDAG.Bifaci.Request.Phase: one of PhaseCreated, PhaseStreaming.
type Phase interface{ isPhase() }

// PhaseCreated is Lean's CapDAG.Bifaci.Request.Phase.created.
type PhaseCreated struct{}

func (PhaseCreated) isPhase() {}

// PhaseStreaming is Lean's CapDAG.Bifaci.Request.Phase.streaming.
type PhaseStreaming struct{}

func (PhaseStreaming) isPhase() {}

// PhaseFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Request.Phase: a package using Phase from this one checks it.
const PhaseFingerprint = "7407437b58ce033618bf82341b13aaa9661d29a5a9b0f1bf1547ea0bfcfd8374"

type phaseDescriptor struct{}

// PhaseType describes CapDAG.Bifaci.Request.Phase for polymorphic functions.
func PhaseType() lungo.Type[Phase] {
	return phaseDescriptor{}
}

func (t phaseDescriptor) Expr() []byte { return lungo.InductiveExpr(12) }

func (t phaseDescriptor) Encode(w *lungo.Writer, v Phase) error {
	switch x := v.(type) {
	case PhaseCreated:
		w.U32(0)
		return nil
	case *PhaseCreated:
		if x == nil {
			return lungo.Malformed("a nil *PhaseCreated")
		}
		return t.Encode(w, *x)
	case PhaseStreaming:
		w.U32(1)
		return nil
	case *PhaseStreaming:
		if x == nil {
			return lungo.Malformed("a nil *PhaseStreaming")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Phase")
}

func (t phaseDescriptor) Decode(r *lungo.Reader) (Phase, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v PhaseCreated
		return v, nil
	case 1:
		var v PhaseStreaming
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Request.Phase", c)
}

// Emitted is Lean's CapDAG.Bifaci.Request.Emitted: one of EmittedStreamStart, EmittedChunk, EmittedStreamEnd, EmittedFin, EmittedErr, EmittedOther.
type Emitted interface{ isEmitted() }

// EmittedStreamStart is Lean's CapDAG.Bifaci.Request.Emitted.streamStart.
type EmittedStreamStart struct {
	Stream string
}

func (EmittedStreamStart) isEmitted() {}

// EmittedChunk is Lean's CapDAG.Bifaci.Request.Emitted.chunk.
type EmittedChunk struct {
	Stream string
	Index  *big.Int
}

func (EmittedChunk) isEmitted() {}

// EmittedStreamEnd is Lean's CapDAG.Bifaci.Request.Emitted.streamEnd.
type EmittedStreamEnd struct {
	Stream string
	Count  lungo.Option[*big.Int]
}

func (EmittedStreamEnd) isEmitted() {}

// EmittedFin is Lean's CapDAG.Bifaci.Request.Emitted.fin.
type EmittedFin struct{}

func (EmittedFin) isEmitted() {}

// EmittedErr is Lean's CapDAG.Bifaci.Request.Emitted.err.
type EmittedErr struct{}

func (EmittedErr) isEmitted() {}

// EmittedOther is Lean's CapDAG.Bifaci.Request.Emitted.other.
type EmittedOther struct{}

func (EmittedOther) isEmitted() {}

// EmittedFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Request.Emitted: a package using Emitted from this one checks it.
const EmittedFingerprint = "97a274be14c5baecf9c50243d3651da838c5de4375366d4102cbcff85fb211c8"

type emittedDescriptor struct{}

// EmittedType describes CapDAG.Bifaci.Request.Emitted for polymorphic functions.
func EmittedType() lungo.Type[Emitted] {
	return emittedDescriptor{}
}

func (t emittedDescriptor) Expr() []byte { return lungo.InductiveExpr(13) }

func (t emittedDescriptor) Encode(w *lungo.Writer, v Emitted) error {
	switch x := v.(type) {
	case EmittedStreamStart:
		w.U32(0)
		if err := lungo.StringType.Encode(w, x.Stream); err != nil {
			return err
		}
		return nil
	case *EmittedStreamStart:
		if x == nil {
			return lungo.Malformed("a nil *EmittedStreamStart")
		}
		return t.Encode(w, *x)
	case EmittedChunk:
		w.U32(1)
		if err := lungo.StringType.Encode(w, x.Stream); err != nil {
			return err
		}
		if err := lungo.NatType.Encode(w, x.Index); err != nil {
			return err
		}
		return nil
	case *EmittedChunk:
		if x == nil {
			return lungo.Malformed("a nil *EmittedChunk")
		}
		return t.Encode(w, *x)
	case EmittedStreamEnd:
		w.U32(2)
		if err := lungo.StringType.Encode(w, x.Stream); err != nil {
			return err
		}
		if err := lungo.OptionType(lungo.NatType).Encode(w, x.Count); err != nil {
			return err
		}
		return nil
	case *EmittedStreamEnd:
		if x == nil {
			return lungo.Malformed("a nil *EmittedStreamEnd")
		}
		return t.Encode(w, *x)
	case EmittedFin:
		w.U32(3)
		return nil
	case *EmittedFin:
		if x == nil {
			return lungo.Malformed("a nil *EmittedFin")
		}
		return t.Encode(w, *x)
	case EmittedErr:
		w.U32(4)
		return nil
	case *EmittedErr:
		if x == nil {
			return lungo.Malformed("a nil *EmittedErr")
		}
		return t.Encode(w, *x)
	case EmittedOther:
		w.U32(5)
		return nil
	case *EmittedOther:
		if x == nil {
			return lungo.Malformed("a nil *EmittedOther")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Emitted")
}

func (t emittedDescriptor) Decode(r *lungo.Reader) (Emitted, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v EmittedStreamStart
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Stream = f0
		return v, nil
	case 1:
		var v EmittedChunk
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Stream = f0
		f1, err := lungo.NatType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Index = f1
		return v, nil
	case 2:
		var v EmittedStreamEnd
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Stream = f0
		f1, err := lungo.OptionType(lungo.NatType).Decode(r)
		if err != nil {
			return nil, err
		}
		v.Count = f1
		return v, nil
	case 3:
		var v EmittedFin
		return v, nil
	case 4:
		var v EmittedErr
		return v, nil
	case 5:
		var v EmittedOther
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Request.Emitted", c)
}

// Violation is Lean's CapDAG.Bifaci.Request.Violation: one of ViolationAfterEnd, ViolationStreamRestarted, ViolationStreamNotOpen, ViolationChunkOutOfPlace, ViolationChunkCountWrong, ViolationEndWithOpenStream.
type Violation interface{ isViolation() }

// ViolationAfterEnd is Lean's CapDAG.Bifaci.Request.Violation.afterEnd.
type ViolationAfterEnd struct{}

func (ViolationAfterEnd) isViolation() {}

// ViolationStreamRestarted is Lean's CapDAG.Bifaci.Request.Violation.streamRestarted.
type ViolationStreamRestarted struct {
	Stream string
}

func (ViolationStreamRestarted) isViolation() {}

// ViolationStreamNotOpen is Lean's CapDAG.Bifaci.Request.Violation.streamNotOpen.
type ViolationStreamNotOpen struct {
	Stream string
}

func (ViolationStreamNotOpen) isViolation() {}

// ViolationChunkOutOfPlace is Lean's CapDAG.Bifaci.Request.Violation.chunkOutOfPlace.
type ViolationChunkOutOfPlace struct {
	Stream   string
	Expected *big.Int
	Got      *big.Int
}

func (ViolationChunkOutOfPlace) isViolation() {}

// ViolationChunkCountWrong is Lean's CapDAG.Bifaci.Request.Violation.chunkCountWrong.
type ViolationChunkCountWrong struct {
	Stream string
	Sent   *big.Int
	Said   *big.Int
}

func (ViolationChunkCountWrong) isViolation() {}

// ViolationEndWithOpenStream is Lean's CapDAG.Bifaci.Request.Violation.endWithOpenStream.
type ViolationEndWithOpenStream struct {
	Stream string
}

func (ViolationEndWithOpenStream) isViolation() {}

// ViolationFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Request.Violation: a package using Violation from this one checks it.
const ViolationFingerprint = "203fb2fc4f8ff3c79b70871b4274852e742adf97c3cc4e6631439ec66d838f09"

type violationDescriptor struct{}

// ViolationType describes CapDAG.Bifaci.Request.Violation for polymorphic functions.
func ViolationType() lungo.Type[Violation] {
	return violationDescriptor{}
}

func (t violationDescriptor) Expr() []byte { return lungo.InductiveExpr(14) }

func (t violationDescriptor) Encode(w *lungo.Writer, v Violation) error {
	switch x := v.(type) {
	case ViolationAfterEnd:
		w.U32(0)
		return nil
	case *ViolationAfterEnd:
		if x == nil {
			return lungo.Malformed("a nil *ViolationAfterEnd")
		}
		return t.Encode(w, *x)
	case ViolationStreamRestarted:
		w.U32(1)
		if err := lungo.StringType.Encode(w, x.Stream); err != nil {
			return err
		}
		return nil
	case *ViolationStreamRestarted:
		if x == nil {
			return lungo.Malformed("a nil *ViolationStreamRestarted")
		}
		return t.Encode(w, *x)
	case ViolationStreamNotOpen:
		w.U32(2)
		if err := lungo.StringType.Encode(w, x.Stream); err != nil {
			return err
		}
		return nil
	case *ViolationStreamNotOpen:
		if x == nil {
			return lungo.Malformed("a nil *ViolationStreamNotOpen")
		}
		return t.Encode(w, *x)
	case ViolationChunkOutOfPlace:
		w.U32(3)
		if err := lungo.StringType.Encode(w, x.Stream); err != nil {
			return err
		}
		if err := lungo.NatType.Encode(w, x.Expected); err != nil {
			return err
		}
		if err := lungo.NatType.Encode(w, x.Got); err != nil {
			return err
		}
		return nil
	case *ViolationChunkOutOfPlace:
		if x == nil {
			return lungo.Malformed("a nil *ViolationChunkOutOfPlace")
		}
		return t.Encode(w, *x)
	case ViolationChunkCountWrong:
		w.U32(4)
		if err := lungo.StringType.Encode(w, x.Stream); err != nil {
			return err
		}
		if err := lungo.NatType.Encode(w, x.Sent); err != nil {
			return err
		}
		if err := lungo.NatType.Encode(w, x.Said); err != nil {
			return err
		}
		return nil
	case *ViolationChunkCountWrong:
		if x == nil {
			return lungo.Malformed("a nil *ViolationChunkCountWrong")
		}
		return t.Encode(w, *x)
	case ViolationEndWithOpenStream:
		w.U32(5)
		if err := lungo.StringType.Encode(w, x.Stream); err != nil {
			return err
		}
		return nil
	case *ViolationEndWithOpenStream:
		if x == nil {
			return lungo.Malformed("a nil *ViolationEndWithOpenStream")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Violation")
}

func (t violationDescriptor) Decode(r *lungo.Reader) (Violation, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v ViolationAfterEnd
		return v, nil
	case 1:
		var v ViolationStreamRestarted
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Stream = f0
		return v, nil
	case 2:
		var v ViolationStreamNotOpen
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Stream = f0
		return v, nil
	case 3:
		var v ViolationChunkOutOfPlace
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Stream = f0
		f1, err := lungo.NatType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Expected = f1
		f2, err := lungo.NatType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Got = f2
		return v, nil
	case 4:
		var v ViolationChunkCountWrong
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Stream = f0
		f1, err := lungo.NatType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Sent = f1
		f2, err := lungo.NatType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Said = f2
		return v, nil
	case 5:
		var v ViolationEndWithOpenStream
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Stream = f0
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Request.Violation", c)
}

// Disposition is Lean's CapDAG.Bifaci.Request.Disposition: one of DispositionRoute, DispositionStraggler, DispositionNoRoute.
type Disposition interface{ isDisposition() }

// DispositionRoute is Lean's CapDAG.Bifaci.Request.Disposition.route.
type DispositionRoute struct{}

func (DispositionRoute) isDisposition() {}

// DispositionStraggler is Lean's CapDAG.Bifaci.Request.Disposition.straggler.
type DispositionStraggler struct{}

func (DispositionStraggler) isDisposition() {}

// DispositionNoRoute is Lean's CapDAG.Bifaci.Request.Disposition.noRoute.
type DispositionNoRoute struct{}

func (DispositionNoRoute) isDisposition() {}

// DispositionFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Request.Disposition: a package using Disposition from this one checks it.
const DispositionFingerprint = "540307dfb6e509ccde4b894c69566edd1f3f9c3223b9325e97ee91b20d0fb82f"

type dispositionDescriptor struct{}

// DispositionType describes CapDAG.Bifaci.Request.Disposition for polymorphic functions.
func DispositionType() lungo.Type[Disposition] {
	return dispositionDescriptor{}
}

func (t dispositionDescriptor) Expr() []byte { return lungo.InductiveExpr(15) }

func (t dispositionDescriptor) Encode(w *lungo.Writer, v Disposition) error {
	switch x := v.(type) {
	case DispositionRoute:
		w.U32(0)
		return nil
	case *DispositionRoute:
		if x == nil {
			return lungo.Malformed("a nil *DispositionRoute")
		}
		return t.Encode(w, *x)
	case DispositionStraggler:
		w.U32(1)
		return nil
	case *DispositionStraggler:
		if x == nil {
			return lungo.Malformed("a nil *DispositionStraggler")
		}
		return t.Encode(w, *x)
	case DispositionNoRoute:
		w.U32(2)
		return nil
	case *DispositionNoRoute:
		if x == nil {
			return lungo.Malformed("a nil *DispositionNoRoute")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Disposition")
}

func (t dispositionDescriptor) Decode(r *lungo.Reader) (Disposition, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v DispositionRoute
		return v, nil
	case 1:
		var v DispositionStraggler
		return v, nil
	case 2:
		var v DispositionNoRoute
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Request.Disposition", c)
}

// Terminal is Lean's CapDAG.Bifaci.Request.Terminal: one of TerminalFinished, TerminalFailed, TerminalCancelled, TerminalMasterDied.
type Terminal interface{ isTerminal() }

// TerminalFinished is Lean's CapDAG.Bifaci.Request.Terminal.finished.
type TerminalFinished struct{}

func (TerminalFinished) isTerminal() {}

// TerminalFailed is Lean's CapDAG.Bifaci.Request.Terminal.failed.
type TerminalFailed struct{}

func (TerminalFailed) isTerminal() {}

// TerminalCancelled is Lean's CapDAG.Bifaci.Request.Terminal.cancelled.
type TerminalCancelled struct{}

func (TerminalCancelled) isTerminal() {}

// TerminalMasterDied is Lean's CapDAG.Bifaci.Request.Terminal.masterDied.
type TerminalMasterDied struct{}

func (TerminalMasterDied) isTerminal() {}

// TerminalFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Request.Terminal: a package using Terminal from this one checks it.
const TerminalFingerprint = "3597c3196cef5e4468b5449eb0da09af414bb8c3aa40d92b027089f6ae81c870"

type terminalDescriptor struct{}

// TerminalType describes CapDAG.Bifaci.Request.Terminal for polymorphic functions.
func TerminalType() lungo.Type[Terminal] {
	return terminalDescriptor{}
}

func (t terminalDescriptor) Expr() []byte { return lungo.InductiveExpr(16) }

func (t terminalDescriptor) Encode(w *lungo.Writer, v Terminal) error {
	switch x := v.(type) {
	case TerminalFinished:
		w.U32(0)
		return nil
	case *TerminalFinished:
		if x == nil {
			return lungo.Malformed("a nil *TerminalFinished")
		}
		return t.Encode(w, *x)
	case TerminalFailed:
		w.U32(1)
		return nil
	case *TerminalFailed:
		if x == nil {
			return lungo.Malformed("a nil *TerminalFailed")
		}
		return t.Encode(w, *x)
	case TerminalCancelled:
		w.U32(2)
		return nil
	case *TerminalCancelled:
		if x == nil {
			return lungo.Malformed("a nil *TerminalCancelled")
		}
		return t.Encode(w, *x)
	case TerminalMasterDied:
		w.U32(3)
		return nil
	case *TerminalMasterDied:
		if x == nil {
			return lungo.Malformed("a nil *TerminalMasterDied")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Terminal")
}

func (t terminalDescriptor) Decode(r *lungo.Reader) (Terminal, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v TerminalFinished
		return v, nil
	case 1:
		var v TerminalFailed
		return v, nil
	case 2:
		var v TerminalCancelled
		return v, nil
	case 3:
		var v TerminalMasterDied
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Request.Terminal", c)
}

// Write is Lean's CapDAG.Bifaci.Request.Write: one of WriteSend, WriteSuppress.
type Write interface{ isWrite() }

// WriteSend is Lean's CapDAG.Bifaci.Request.Write.send.
type WriteSend struct {
	Ends bool
}

func (WriteSend) isWrite() {}

// WriteSuppress is Lean's CapDAG.Bifaci.Request.Write.suppress.
type WriteSuppress struct{}

func (WriteSuppress) isWrite() {}

// WriteFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Request.Write: a package using Write from this one checks it.
const WriteFingerprint = "9ae21282903c8131c25ca1cc527e51fd1fa5137aa77c9ef4f3d091e9415a109a"

type writeDescriptor struct{}

// WriteType describes CapDAG.Bifaci.Request.Write for polymorphic functions.
func WriteType() lungo.Type[Write] {
	return writeDescriptor{}
}

func (t writeDescriptor) Expr() []byte { return lungo.InductiveExpr(17) }

func (t writeDescriptor) Encode(w *lungo.Writer, v Write) error {
	switch x := v.(type) {
	case WriteSend:
		w.U32(0)
		if err := lungo.BoolType.Encode(w, x.Ends); err != nil {
			return err
		}
		return nil
	case *WriteSend:
		if x == nil {
			return lungo.Malformed("a nil *WriteSend")
		}
		return t.Encode(w, *x)
	case WriteSuppress:
		w.U32(1)
		return nil
	case *WriteSuppress:
		if x == nil {
			return lungo.Malformed("a nil *WriteSuppress")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Write")
}

func (t writeDescriptor) Decode(r *lungo.Reader) (Write, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v WriteSend
		f0, err := lungo.BoolType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Ends = f0
		return v, nil
	case 1:
		var v WriteSuppress
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Request.Write", c)
}

// WfCap is Lean's CapDAG.Exec.WfCap.
type WfCap struct {
	Input  formal.Wf
	Output formal.Wf
	Other  formal.Wf
	Effect Effect
}

// WfCapFingerprint is the layout fingerprint of Lean's CapDAG.Exec.WfCap: a package using WfCap from this one checks it.
const WfCapFingerprint = "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830"

type wfCapDescriptor struct{}

// WfCapType describes CapDAG.Exec.WfCap for polymorphic functions.
func WfCapType() lungo.Type[WfCap] {
	return wfCapDescriptor{}
}

func (t wfCapDescriptor) Expr() []byte { return lungo.InductiveExpr(18) }

func (t wfCapDescriptor) Encode(w *lungo.Writer, v WfCap) error {
	w.U32(0)
	if err := extWfType().Encode(w, v.Input); err != nil {
		return err
	}
	if err := extWfType().Encode(w, v.Output); err != nil {
		return err
	}
	if err := extWfType().Encode(w, v.Other); err != nil {
		return err
	}
	if err := EffectType().Encode(w, v.Effect); err != nil {
		return err
	}
	return nil
}

func (t wfCapDescriptor) Decode(r *lungo.Reader) (WfCap, error) {
	var v WfCap
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Exec.WfCap", c)
	}
	f0, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Input = f0
	f1, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Output = f1
	f2, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Other = f2
	f3, err := EffectType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Effect = f3
	return v, nil
}

// Effect is Lean's CapDAG.Effect: one of EffectUnspecified, EffectDeclared, EffectNone, EffectPatch.
type Effect interface{ isEffect() }

// EffectUnspecified is Lean's CapDAG.Effect.unspecified.
type EffectUnspecified struct{}

func (EffectUnspecified) isEffect() {}

// EffectDeclared is Lean's CapDAG.Effect.declared.
type EffectDeclared struct{}

func (EffectDeclared) isEffect() {}

// EffectNone is Lean's CapDAG.Effect.none.
type EffectNone struct{}

func (EffectNone) isEffect() {}

// EffectPatch is Lean's CapDAG.Effect.patch.
type EffectPatch struct{}

func (EffectPatch) isEffect() {}

// EffectFingerprint is the layout fingerprint of Lean's CapDAG.Effect: a package using Effect from this one checks it.
const EffectFingerprint = "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477"

type effectDescriptor struct{}

// EffectType describes CapDAG.Effect for polymorphic functions.
func EffectType() lungo.Type[Effect] {
	return effectDescriptor{}
}

func (t effectDescriptor) Expr() []byte { return lungo.InductiveExpr(19) }

func (t effectDescriptor) Encode(w *lungo.Writer, v Effect) error {
	switch x := v.(type) {
	case EffectUnspecified:
		w.U32(0)
		return nil
	case *EffectUnspecified:
		if x == nil {
			return lungo.Malformed("a nil *EffectUnspecified")
		}
		return t.Encode(w, *x)
	case EffectDeclared:
		w.U32(1)
		return nil
	case *EffectDeclared:
		if x == nil {
			return lungo.Malformed("a nil *EffectDeclared")
		}
		return t.Encode(w, *x)
	case EffectNone:
		w.U32(2)
		return nil
	case *EffectNone:
		if x == nil {
			return lungo.Malformed("a nil *EffectNone")
		}
		return t.Encode(w, *x)
	case EffectPatch:
		w.U32(3)
		return nil
	case *EffectPatch:
		if x == nil {
			return lungo.Malformed("a nil *EffectPatch")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Effect")
}

func (t effectDescriptor) Decode(r *lungo.Reader) (Effect, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v EffectUnspecified
		return v, nil
	case 1:
		var v EffectDeclared
		return v, nil
	case 2:
		var v EffectNone
		return v, nil
	case 3:
		var v EffectPatch
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Effect", c)
}

// WfQuery is Lean's CapDAG.Exec.WfQuery.
type WfQuery struct {
	Input  WfAsk
	Output WfAsk
	Tags   formal.Wf
	Effect Effect
}

// WfQueryFingerprint is the layout fingerprint of Lean's CapDAG.Exec.WfQuery: a package using WfQuery from this one checks it.
const WfQueryFingerprint = "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e"

type wfQueryDescriptor struct{}

// WfQueryType describes CapDAG.Exec.WfQuery for polymorphic functions.
func WfQueryType() lungo.Type[WfQuery] {
	return wfQueryDescriptor{}
}

func (t wfQueryDescriptor) Expr() []byte { return lungo.InductiveExpr(20) }

func (t wfQueryDescriptor) Encode(w *lungo.Writer, v WfQuery) error {
	w.U32(0)
	if err := WfAskType().Encode(w, v.Input); err != nil {
		return err
	}
	if err := WfAskType().Encode(w, v.Output); err != nil {
		return err
	}
	if err := extWfType().Encode(w, v.Tags); err != nil {
		return err
	}
	if err := EffectType().Encode(w, v.Effect); err != nil {
		return err
	}
	return nil
}

func (t wfQueryDescriptor) Decode(r *lungo.Reader) (WfQuery, error) {
	var v WfQuery
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Exec.WfQuery", c)
	}
	f0, err := WfAskType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Input = f0
	f1, err := WfAskType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Output = f1
	f2, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Tags = f2
	f3, err := EffectType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Effect = f3
	return v, nil
}

type extWfDescriptor struct{}

// extWfType describes Lean's TaggedUrn.Exec.Wf, provided by github.com/machinefabric/tagged-urn-go/formal.
func extWfType() lungo.Type[formal.Wf] {
	return extWfDescriptor{}
}

func (t extWfDescriptor) Expr() []byte { return lungo.InductiveExpr(21) }
func (t extWfDescriptor) Encode(w *lungo.Writer, v formal.Wf) error {
	return formal.WfType().Encode(w, v)
}
func (t extWfDescriptor) Decode(r *lungo.Reader) (formal.Wf, error) {
	return formal.WfType().Decode(r)
}

// Grade is Lean's CapDAG.Grade: one of GradeExact, GradeGuaranteed, GradePossible, GradeNone.
type Grade interface{ isGrade() }

// GradeExact is Lean's CapDAG.Grade.exact.
type GradeExact struct{}

func (GradeExact) isGrade() {}

// GradeGuaranteed is Lean's CapDAG.Grade.guaranteed.
type GradeGuaranteed struct{}

func (GradeGuaranteed) isGrade() {}

// GradePossible is Lean's CapDAG.Grade.possible.
type GradePossible struct{}

func (GradePossible) isGrade() {}

// GradeNone is Lean's CapDAG.Grade.none.
type GradeNone struct{}

func (GradeNone) isGrade() {}

// GradeFingerprint is the layout fingerprint of Lean's CapDAG.Grade: a package using Grade from this one checks it.
const GradeFingerprint = "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2"

type gradeDescriptor struct{}

// GradeType describes CapDAG.Grade for polymorphic functions.
func GradeType() lungo.Type[Grade] {
	return gradeDescriptor{}
}

func (t gradeDescriptor) Expr() []byte { return lungo.InductiveExpr(22) }

func (t gradeDescriptor) Encode(w *lungo.Writer, v Grade) error {
	switch x := v.(type) {
	case GradeExact:
		w.U32(0)
		return nil
	case *GradeExact:
		if x == nil {
			return lungo.Malformed("a nil *GradeExact")
		}
		return t.Encode(w, *x)
	case GradeGuaranteed:
		w.U32(1)
		return nil
	case *GradeGuaranteed:
		if x == nil {
			return lungo.Malformed("a nil *GradeGuaranteed")
		}
		return t.Encode(w, *x)
	case GradePossible:
		w.U32(2)
		return nil
	case *GradePossible:
		if x == nil {
			return lungo.Malformed("a nil *GradePossible")
		}
		return t.Encode(w, *x)
	case GradeNone:
		w.U32(3)
		return nil
	case *GradeNone:
		if x == nil {
			return lungo.Malformed("a nil *GradeNone")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Grade")
}

func (t gradeDescriptor) Decode(r *lungo.Reader) (Grade, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v GradeExact
		return v, nil
	case 1:
		var v GradeGuaranteed
		return v, nil
	case 2:
		var v GradePossible
		return v, nil
	case 3:
		var v GradeNone
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Grade", c)
}

// Constraint is Lean's TaggedUrn.Constraint: one of ConstraintMissing, ConstraintUnconstrained, ConstraintOptionalNot, ConstraintPresent, ConstraintPresentNot, ConstraintExact, ConstraintAbsent.
type Constraint interface{ isConstraint() }

// ConstraintMissing is Lean's TaggedUrn.Constraint.missing.
type ConstraintMissing struct{}

func (ConstraintMissing) isConstraint() {}

// ConstraintUnconstrained is Lean's TaggedUrn.Constraint.unconstrained.
type ConstraintUnconstrained struct{}

func (ConstraintUnconstrained) isConstraint() {}

// ConstraintOptionalNot is Lean's TaggedUrn.Constraint.optionalNot.
type ConstraintOptionalNot struct {
	Value string
}

func (ConstraintOptionalNot) isConstraint() {}

// ConstraintPresent is Lean's TaggedUrn.Constraint.present.
type ConstraintPresent struct{}

func (ConstraintPresent) isConstraint() {}

// ConstraintPresentNot is Lean's TaggedUrn.Constraint.presentNot.
type ConstraintPresentNot struct {
	Value string
}

func (ConstraintPresentNot) isConstraint() {}

// ConstraintExact is Lean's TaggedUrn.Constraint.exact.
type ConstraintExact struct {
	Value string
}

func (ConstraintExact) isConstraint() {}

// ConstraintAbsent is Lean's TaggedUrn.Constraint.absent.
type ConstraintAbsent struct{}

func (ConstraintAbsent) isConstraint() {}

// ConstraintFingerprint is the layout fingerprint of Lean's TaggedUrn.Constraint: a package using Constraint from this one checks it.
const ConstraintFingerprint = "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"

type constraintDescriptor struct{}

// ConstraintType describes TaggedUrn.Constraint for polymorphic functions.
func ConstraintType() lungo.Type[Constraint] {
	return constraintDescriptor{}
}

func (t constraintDescriptor) Expr() []byte { return lungo.InductiveExpr(23) }

func (t constraintDescriptor) Encode(w *lungo.Writer, v Constraint) error {
	switch x := v.(type) {
	case ConstraintMissing:
		w.U32(0)
		return nil
	case *ConstraintMissing:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintMissing")
		}
		return t.Encode(w, *x)
	case ConstraintUnconstrained:
		w.U32(1)
		return nil
	case *ConstraintUnconstrained:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintUnconstrained")
		}
		return t.Encode(w, *x)
	case ConstraintOptionalNot:
		w.U32(2)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintOptionalNot:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintOptionalNot")
		}
		return t.Encode(w, *x)
	case ConstraintPresent:
		w.U32(3)
		return nil
	case *ConstraintPresent:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintPresent")
		}
		return t.Encode(w, *x)
	case ConstraintPresentNot:
		w.U32(4)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintPresentNot:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintPresentNot")
		}
		return t.Encode(w, *x)
	case ConstraintExact:
		w.U32(5)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintExact:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintExact")
		}
		return t.Encode(w, *x)
	case ConstraintAbsent:
		w.U32(6)
		return nil
	case *ConstraintAbsent:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintAbsent")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Constraint")
}

func (t constraintDescriptor) Decode(r *lungo.Reader) (Constraint, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v ConstraintMissing
		return v, nil
	case 1:
		var v ConstraintUnconstrained
		return v, nil
	case 2:
		var v ConstraintOptionalNot
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 3:
		var v ConstraintPresent
		return v, nil
	case 4:
		var v ConstraintPresentNot
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 5:
		var v ConstraintExact
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 6:
		var v ConstraintAbsent
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of TaggedUrn.Constraint", c)
}

// Pool is Lean's CapDAG.Bifaci.Pools.Pool.
type Pool struct {
	Name     string
	Capacity *big.Int
	Active   *big.Int
}

// PoolFingerprint is the layout fingerprint of Lean's CapDAG.Bifaci.Pools.Pool: a package using Pool from this one checks it.
const PoolFingerprint = "60bca9d670886c7830c76779ad692b4fbb6e4e30c0ce6b3e9d5a91a9b5b7b1e6"

type poolDescriptor struct{}

// PoolType describes CapDAG.Bifaci.Pools.Pool for polymorphic functions.
func PoolType() lungo.Type[Pool] {
	return poolDescriptor{}
}

func (t poolDescriptor) Expr() []byte { return lungo.InductiveExpr(24) }

func (t poolDescriptor) Encode(w *lungo.Writer, v Pool) error {
	w.U32(0)
	if err := lungo.StringType.Encode(w, v.Name); err != nil {
		return err
	}
	if err := lungo.NatType.Encode(w, v.Capacity); err != nil {
		return err
	}
	if err := lungo.NatType.Encode(w, v.Active); err != nil {
		return err
	}
	return nil
}

func (t poolDescriptor) Decode(r *lungo.Reader) (Pool, error) {
	var v Pool
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Bifaci.Pools.Pool", c)
	}
	f0, err := lungo.StringType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Name = f0
	f1, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Capacity = f1
	f2, err := lungo.NatType.Decode(r)
	if err != nil {
		return v, err
	}
	v.Active = f2
	return v, nil
}

// WfAsk is Lean's CapDAG.Exec.WfAsk: one of WfAskUnknown, WfAskWithin, WfAskCovers, WfAskSame.
type WfAsk interface{ isWfAsk() }

// WfAskUnknown is Lean's CapDAG.Exec.WfAsk.unknown.
type WfAskUnknown struct{}

func (WfAskUnknown) isWfAsk() {}

// WfAskWithin is Lean's CapDAG.Exec.WfAsk.within.
type WfAskWithin struct {
	U formal.Wf
}

func (WfAskWithin) isWfAsk() {}

// WfAskCovers is Lean's CapDAG.Exec.WfAsk.covers.
type WfAskCovers struct {
	U formal.Wf
}

func (WfAskCovers) isWfAsk() {}

// WfAskSame is Lean's CapDAG.Exec.WfAsk.same.
type WfAskSame struct {
	U formal.Wf
}

func (WfAskSame) isWfAsk() {}

// WfAskFingerprint is the layout fingerprint of Lean's CapDAG.Exec.WfAsk: a package using WfAsk from this one checks it.
const WfAskFingerprint = "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952"

type wfAskDescriptor struct{}

// WfAskType describes CapDAG.Exec.WfAsk for polymorphic functions.
func WfAskType() lungo.Type[WfAsk] {
	return wfAskDescriptor{}
}

func (t wfAskDescriptor) Expr() []byte { return lungo.InductiveExpr(25) }

func (t wfAskDescriptor) Encode(w *lungo.Writer, v WfAsk) error {
	switch x := v.(type) {
	case WfAskUnknown:
		w.U32(0)
		return nil
	case *WfAskUnknown:
		if x == nil {
			return lungo.Malformed("a nil *WfAskUnknown")
		}
		return t.Encode(w, *x)
	case WfAskWithin:
		w.U32(1)
		if err := extWfType().Encode(w, x.U); err != nil {
			return err
		}
		return nil
	case *WfAskWithin:
		if x == nil {
			return lungo.Malformed("a nil *WfAskWithin")
		}
		return t.Encode(w, *x)
	case WfAskCovers:
		w.U32(2)
		if err := extWfType().Encode(w, x.U); err != nil {
			return err
		}
		return nil
	case *WfAskCovers:
		if x == nil {
			return lungo.Malformed("a nil *WfAskCovers")
		}
		return t.Encode(w, *x)
	case WfAskSame:
		w.U32(3)
		if err := extWfType().Encode(w, x.U); err != nil {
			return err
		}
		return nil
	case *WfAskSame:
		if x == nil {
			return lungo.Malformed("a nil *WfAskSame")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil WfAsk")
}

func (t wfAskDescriptor) Decode(r *lungo.Reader) (WfAsk, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v WfAskUnknown
		return v, nil
	case 1:
		var v WfAskWithin
		f0, err := extWfType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.U = f0
		return v, nil
	case 2:
		var v WfAskCovers
		f0, err := extWfType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.U = f0
		return v, nil
	case 3:
		var v WfAskSame
		f0, err := extWfType().Decode(r)
		if err != nil {
			return nil, err
		}
		v.U = f0
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Exec.WfAsk", c)
}

// GateAcquire is Lean's CapDAG.Bifaci.Credit.Gate.acquire : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Acquire
func GateAcquire(g Gate, n *big.Int) (result Acquire, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = GateType().Encode(w, g); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, n); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dacquire), w.Bytes())
	return lungo.DecodeValue(program(), status, out, AcquireType())
}

// Close is Lean's CapDAG.Bifaci.Credit.Gate.close : CapDAG.Bifaci.Credit.Gate → String → CapDAG.Bifaci.Credit.Gate
func Close(g Gate, reason string) (result Gate, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = GateType().Encode(w, g); err != nil {
		return
	}
	if err = lungo.StringType.Encode(w, reason); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dclose), w.Bytes())
	return lungo.DecodeValue(program(), status, out, GateType())
}

// Grant is Lean's CapDAG.Bifaci.Credit.Gate.grant : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Gate
func Grant(g Gate, n *big.Int) (result Gate, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = GateType().Encode(w, g); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, n); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dgrant), w.Bytes())
	return lungo.DecodeValue(program(), status, out, GateType())
}

// GateOpened is Lean's CapDAG.Bifaci.Credit.Gate.opened : Nat → CapDAG.Bifaci.Credit.Gate
func GateOpened(window *big.Int) (result Gate, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.NatType.Encode(w, window); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dopened), w.Bytes())
	return lungo.DecodeValue(program(), status, out, GateType())
}

// WindowArrive is Lean's CapDAG.Bifaci.Credit.Window.arrive : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Arrival
func WindowArrive(w_ Window) (result CreditArrival, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WindowType().Encode(w, w_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_darrive), w.Bytes())
	return lungo.DecodeValue(program(), status, out, CreditArrivalType())
}

// Consume is Lean's CapDAG.Bifaci.Credit.Window.consume : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted
func Consume(w_ Window) (result Granted, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WindowType().Encode(w, w_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dconsume), w.Bytes())
	return lungo.DecodeValue(program(), status, out, GrantedType())
}

// Continued is Lean's CapDAG.Bifaci.Credit.Window.continued : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted
func Continued(w_ Window) (result Granted, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WindowType().Encode(w, w_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dcontinued), w.Bytes())
	return lungo.DecodeValue(program(), status, out, GrantedType())
}

// Flush is Lean's CapDAG.Bifaci.Credit.Window.flush : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted
func Flush(w_ Window) (result Granted, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WindowType().Encode(w, w_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dflush), w.Bytes())
	return lungo.DecodeValue(program(), status, out, GrantedType())
}

// WindowOpened is Lean's CapDAG.Bifaci.Credit.Window.opened : Nat → CapDAG.Bifaci.Credit.Window
func WindowOpened(window *big.Int) (result Window, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.NatType.Encode(w, window); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dopened), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WindowType())
}

// GrantTarget is Lean's CapDAG.Bifaci.Credit.grantTarget : List (Option String) → Option String → Option (Option String)
func GrantTarget(streams []lungo.Option[string], named lungo.Option[string]) (result lungo.Option[lungo.Option[string]], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.ListType(lungo.OptionType(lungo.StringType)).Encode(w, streams); err != nil {
		return
	}
	if err = lungo.OptionType(lungo.StringType).Encode(w, named); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dgrantTarget), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(lungo.OptionType(lungo.StringType)))
}

// Negotiate is Lean's CapDAG.Bifaci.Credit.negotiate : Nat → Nat → Option Nat
func Negotiate(ours *big.Int, theirs *big.Int) (result lungo.Option[*big.Int], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.NatType.Encode(w, ours); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, theirs); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dCredit_dnegotiate), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(lungo.NatType))
}

// Code is Lean's CapDAG.Bifaci.Flow.FrameType.code : CapDAG.Bifaci.Flow.FrameType → Nat
func Code(a FrameType) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = FrameTypeType().Encode(w, a); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_dcode), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// IsFlow is Lean's CapDAG.Bifaci.Flow.FrameType.isFlow : CapDAG.Bifaci.Flow.FrameType → Bool
func IsFlow(a FrameType) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = FrameTypeType().Encode(w, a); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_disFlow), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// IsTerminal is Lean's CapDAG.Bifaci.Flow.FrameType.isTerminal : CapDAG.Bifaci.Flow.FrameType → Bool
func IsTerminal(a FrameType) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = FrameTypeType().Encode(w, a); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_disTerminal), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// OfCode is Lean's CapDAG.Bifaci.Flow.FrameType.ofCode : Nat → Option CapDAG.Bifaci.Flow.FrameType
func OfCode(a *big.Int) (result lungo.Option[FrameType], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.NatType.Encode(w, a); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_dofCode), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(FrameTypeType()))
}

// Accept is Lean's CapDAG.Bifaci.Flow.Reorder.accept : CapDAG.Bifaci.Flow.Reorder → Nat → Nat → CapDAG.Bifaci.Flow.Accepted
func Accept(r_ Reorder, seq *big.Int, limit *big.Int) (result Accepted, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = ReorderType().Encode(w, r_); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, seq); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, limit); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dFlow_dReorder_daccept), w.Bytes())
	return lungo.DecodeValue(program(), status, out, AcceptedType())
}

// Start is Lean's CapDAG.Bifaci.Flow.Reorder.start : CapDAG.Bifaci.Flow.Reorder
func Start() (result Reorder, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dFlow_dReorder_dstart), w.Bytes())
	return lungo.DecodeValue(program(), status, out, ReorderType())
}

// Admit is Lean's CapDAG.Bifaci.Pools.State.admit : CapDAG.Bifaci.Pools.State → Nat → Option CapDAG.Bifaci.Pools.State
func Admit(s State, ticket *big.Int) (result lungo.Option[State], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, ticket); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dadmit), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(StateType()))
}

// AdmitNext is Lean's CapDAG.Bifaci.Pools.State.admitNext : CapDAG.Bifaci.Pools.State → Option (CapDAG.Bifaci.Pools.Waiter × CapDAG.Bifaci.Pools.State)
func AdmitNext(s State) (result lungo.Option[lungo.Pair[Waiter, State]], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dadmitNext), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(lungo.PairType(WaiterType(), StateType())))
}

// StateArrive is Lean's CapDAG.Bifaci.Pools.State.arrive : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival
func StateArrive(s State, chain []string) (result PoolsArrival, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.ListType(lungo.StringType).Encode(w, chain); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_darrive), w.Bytes())
	return lungo.DecodeValue(program(), status, out, PoolsArrivalType())
}

// Empty is Lean's CapDAG.Bifaci.Pools.State.empty : CapDAG.Bifaci.Pools.State
func Empty() (result State, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dempty), w.Bytes())
	return lungo.DecodeValue(program(), status, out, StateType())
}

// HasRoom is Lean's CapDAG.Bifaci.Pools.State.hasRoom : CapDAG.Bifaci.Pools.State → List String → Bool
func HasRoom(s State, chain []string) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.ListType(lungo.StringType).Encode(w, chain); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dhasRoom), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// HeldBack is Lean's CapDAG.Bifaci.Pools.State.heldBack : CapDAG.Bifaci.Pools.State → String → Nat
func HeldBack(s State, name string) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.StringType.Encode(w, name); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dheldBack), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// Join is Lean's CapDAG.Bifaci.Pools.State.join : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival
func Join(s State, chain []string) (result PoolsArrival, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.ListType(lungo.StringType).Encode(w, chain); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_djoin), w.Bytes())
	return lungo.DecodeValue(program(), status, out, PoolsArrivalType())
}

// Leave is Lean's CapDAG.Bifaci.Pools.State.leave : CapDAG.Bifaci.Pools.State → Nat → CapDAG.Bifaci.Pools.State
func Leave(s State, ticket *big.Int) (result State, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, ticket); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dleave), w.Bytes())
	return lungo.DecodeValue(program(), status, out, StateType())
}

// Position is Lean's CapDAG.Bifaci.Pools.State.position : CapDAG.Bifaci.Pools.State → Nat → Nat
func Position(s State, ticket *big.Int) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, ticket); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dposition), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// Release is Lean's CapDAG.Bifaci.Pools.State.release : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.State
func Release(s State, chain []string) (result State, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.ListType(lungo.StringType).Encode(w, chain); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_drelease), w.Bytes())
	return lungo.DecodeValue(program(), status, out, StateType())
}

// SetCapacity is Lean's CapDAG.Bifaci.Pools.State.setCapacity : CapDAG.Bifaci.Pools.State → String → Nat → CapDAG.Bifaci.Pools.State
func SetCapacity(s State, name string, capacity *big.Int) (result State, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = StateType().Encode(w, s); err != nil {
		return
	}
	if err = lungo.StringType.Encode(w, name); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, capacity); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dsetCapacity), w.Bytes())
	return lungo.DecodeValue(program(), status, out, StateType())
}

// Advertised is Lean's CapDAG.Bifaci.Pools.advertised : Bool → String → Nat → Option Nat → Nat
func Advertised(running bool, pool string, configured *big.Int, available lungo.Option[*big.Int]) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.BoolType.Encode(w, running); err != nil {
		return
	}
	if err = lungo.StringType.Encode(w, pool); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, configured); err != nil {
		return
	}
	if err = lungo.OptionType(lungo.NatType).Encode(w, available); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dadvertised), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// Chain is Lean's CapDAG.Bifaci.Pools.chain : String → List (String × List String) → List String
func Chain(cap_ string, shared []lungo.Pair[string, []string]) (result []string, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.StringType.Encode(w, cap_); err != nil {
		return
	}
	if err = lungo.ListType(lungo.PairType(lungo.StringType, lungo.ListType(lungo.StringType))).Encode(w, shared); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dchain), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.ListType(lungo.StringType))
}

// Effective is Lean's CapDAG.Bifaci.Pools.effective : Nat → Option Nat → Nat
func Effective(configured *big.Int, available lungo.Option[*big.Int]) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.NatType.Encode(w, configured); err != nil {
		return
	}
	if err = lungo.OptionType(lungo.NatType).Encode(w, available); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_deffective), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// PoolsPatience is Lean's CapDAG.Bifaci.Pools.patience : Option Nat → Nat → CapDAG.Bifaci.Pools.Patience
func PoolsPatience(unavailableFor lungo.Option[*big.Int], grace *big.Int) (result Patience, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.OptionType(lungo.NatType).Encode(w, unavailableFor); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, grace); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dPools_dpatience), w.Bytes())
	return lungo.DecodeValue(program(), status, out, PatienceType())
}

// After is Lean's CapDAG.Bifaci.Request.Phase.after : CapDAG.Bifaci.Request.Phase → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Phase
func After(p_ Phase, frame FrameType) (result Phase, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = PhaseType().Encode(w, p_); err != nil {
		return
	}
	if err = FrameTypeType().Encode(w, frame); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dRequest_dPhase_dafter), w.Bytes())
	return lungo.DecodeValue(program(), status, out, PhaseType())
}

// Check is Lean's CapDAG.Bifaci.Request.check : List CapDAG.Bifaci.Request.Emitted → Option CapDAG.Bifaci.Request.Violation
func Check(frames []Emitted) (result lungo.Option[Violation], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.ListType(EmittedType()).Encode(w, frames); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dRequest_dcheck), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(ViolationType()))
}

// Dispose is Lean's CapDAG.Bifaci.Request.dispose : Bool → Bool → CapDAG.Bifaci.Request.Disposition
func Dispose(live bool, endedLately bool) (result Disposition, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.BoolType.Encode(w, live); err != nil {
		return
	}
	if err = lungo.BoolType.Encode(w, endedLately); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dRequest_ddispose), w.Bytes())
	return lungo.DecodeValue(program(), status, out, DispositionType())
}

// Ledger is Lean's CapDAG.Bifaci.Request.ledger : Int → CapDAG.Bifaci.Flow.FrameType → Nat → Int
func Ledger(remaining *big.Int, frame FrameType, granted *big.Int) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.IntType.Encode(w, remaining); err != nil {
		return
	}
	if err = FrameTypeType().Encode(w, frame); err != nil {
		return
	}
	if err = lungo.NatType.Encode(w, granted); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dRequest_dledger), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.IntType)
}

// TerminalOf is Lean's CapDAG.Bifaci.Request.terminalOf : CapDAG.Bifaci.Flow.FrameType → Option CapDAG.Bifaci.Request.Terminal
func TerminalOf(a FrameType) (result lungo.Option[Terminal], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = FrameTypeType().Encode(w, a); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dRequest_dterminalOf), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(TerminalType()))
}

// RequestWrite is Lean's CapDAG.Bifaci.Request.write : Bool → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Write
func RequestWrite(over bool, frame FrameType) (result Write, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.BoolType.Encode(w, over); err != nil {
		return
	}
	if err = FrameTypeType().Encode(w, frame); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dBifaci_dRequest_dwrite), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WriteType())
}

// Accepts is Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Accepts(pattern WfCap, cap_ WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, pattern); err != nil {
		return
	}
	if err = WfCapType().Encode(w, cap_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_daccepts), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Comparable is Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Comparable(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dcomparable), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Dispatch is Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Dispatch(candidate WfCap, request WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, candidate); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_ddispatch), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// EffectOk is Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool
func EffectOk(candidate Effect, request Effect) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = EffectType().Encode(w, candidate); err != nil {
		return
	}
	if err = EffectType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_deffectOk), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Equivalent is Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Equivalent(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dequivalent), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Flows is Lean's CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Flows(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dflows), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// MayDispatch is Lean's CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func MayDispatch(candidate WfCap, request WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, candidate); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dmayDispatch), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// MayFlow is Lean's CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func MayFlow(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dmayFlow), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// QueryAdmits is Lean's CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool
func QueryAdmits(q WfQuery, c_ WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfQueryType().Encode(w, q); err != nil {
		return
	}
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryAdmits), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// QueryBetween is Lean's CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
func QueryBetween(input formal.Wf, output formal.Wf, tags formal.Wf) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = extWfType().Encode(w, input); err != nil {
		return
	}
	if err = extWfType().Encode(w, output); err != nil {
		return
	}
	if err = extWfType().Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryBetween), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// QueryConsuming is Lean's CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
func QueryConsuming(input formal.Wf, tags formal.Wf) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = extWfType().Encode(w, input); err != nil {
		return
	}
	if err = extWfType().Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryConsuming), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// QueryGrade is Lean's CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade
func QueryGrade(q WfQuery, c_ WfCap) (result Grade, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfQueryType().Encode(w, q); err != nil {
		return
	}
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryGrade), w.Bytes())
	return lungo.DecodeValue(program(), status, out, GradeType())
}

// QueryMayAdmit is Lean's CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool
func QueryMayAdmit(q WfQuery, c_ WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfQueryType().Encode(w, q); err != nil {
		return
	}
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryMayAdmit), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// QueryOfPattern is Lean's CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery
func QueryOfPattern(p_ WfCap) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, p_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryOfPattern), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// QueryOfRequest is Lean's CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery
func QueryOfRequest(r_ WfCap) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, r_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryOfRequest), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// QueryProducing is Lean's CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery
func QueryProducing(output formal.Wf, tags formal.Wf) (result WfQuery, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = extWfType().Encode(w, output); err != nil {
		return
	}
	if err = extWfType().Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dqueryProducing), w.Bytes())
	return lungo.DecodeValue(program(), status, out, WfQueryType())
}

// RankingKey is Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat
func RankingKey(candidate WfCap, request WfCap) (result lungo.Pair[*big.Int, *big.Int], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, candidate); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_drankingKey), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.PairType(lungo.NatType, lungo.NatType))
}

// Select is Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap
func Select(candidates []WfCap, request WfCap) (result lungo.Option[WfCap], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.ListType(WfCapType()).Encode(w, candidates); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dselect), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(WfCapType()))
}

// Specificity is Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat
func Specificity(c_ WfCap) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dspecificity), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// Make is Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf
func Make(scheme string, tags []lungo.Pair[string, Constraint]) (result lungo.Option[formal.Wf], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.StringType.Encode(w, scheme); err != nil {
		return
	}
	if err = lungo.ListType(lungo.PairType(lungo.StringType, ConstraintType())).Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_TaggedUrn_dExec_dmake), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(extWfType()))
}
