// Code generated by lungo 1.156.5900 from Lean 4.34.1 for program capdagFormal; DO NOT EDIT.

// Package formal calls the Lean program capdagFormal (generated by lungo).
package formal

/*
#cgo CFLAGS: -I${SRCDIR}
#include <stdlib.h>
#include "capdagFormal_program.h"

static int32_t capdagFormal_go_call(lungo_entry f, const uint8_t *in, size_t n, lungo_buffer *out) { return f(in, n, out); }
*/
import "C"

import (
	"math/big"
	"sync"
	"unsafe"

	lungo "github.com/machinefabric/lungo-go"
	formal "github.com/machinefabric/tagged-urn-go/formal"
)

// Generated for exactly this version of the support module.
const _ = lungo.EnforceVersion1_156_5900

var programOnce sync.Once
var theProgram *lungo.Program

func program() *lungo.Program {
	programOnce.Do(func() { theProgram = lungo.NewProgram(unsafe.Pointer(C.capdagFormal__types())) })
	return theProgram
}

func call(entry C.lungo_entry, in []byte) (int32, []byte) {
	var buf C.lungo_buffer
	var p *C.uint8_t
	if len(in) > 0 {
		p = (*C.uint8_t)(unsafe.Pointer(&in[0]))
	}
	status := C.capdagFormal_go_call(entry, p, C.size_t(len(in)), &buf)
	var out []byte
	if buf.len > 0 {
		out = C.GoBytes(unsafe.Pointer(buf.data), C.int(buf.len))
	}
	C.lungo_buffer_free(&buf)
	return int32(status), out
}

// The packages providing this program's extern types were generated for the layouts it was.
func init() {
	if formal.WfFingerprint != "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785" {
		panic("TaggedUrn.Exec.Wf of github.com/machinefabric/tagged-urn-go/formal has another layout than the one this program was generated for: regenerate both from the same Lean definition")
	}
}

// WfCap is Lean's CapDAG.Exec.WfCap.
type WfCap struct {
	Input  formal.Wf
	Output formal.Wf
	Other  formal.Wf
	Effect Effect
}

// WfCapFingerprint is the layout fingerprint of Lean's CapDAG.Exec.WfCap: a package using WfCap from this one checks it.
const WfCapFingerprint = "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830"

type wfCapDescriptor struct{}

// WfCapType describes CapDAG.Exec.WfCap for polymorphic functions.
func WfCapType() lungo.Type[WfCap] {
	return wfCapDescriptor{}
}

func (t wfCapDescriptor) Expr() []byte { return lungo.InductiveExpr(0) }

func (t wfCapDescriptor) Encode(w *lungo.Writer, v WfCap) error {
	w.U32(0)
	if err := extWfType().Encode(w, v.Input); err != nil {
		return err
	}
	if err := extWfType().Encode(w, v.Output); err != nil {
		return err
	}
	if err := extWfType().Encode(w, v.Other); err != nil {
		return err
	}
	if err := EffectType().Encode(w, v.Effect); err != nil {
		return err
	}
	return nil
}

func (t wfCapDescriptor) Decode(r *lungo.Reader) (WfCap, error) {
	var v WfCap
	c, err := r.U32()
	if err != nil {
		return v, err
	}
	if c != 0 {
		return v, lungo.Malformed("constructor index %d of CapDAG.Exec.WfCap", c)
	}
	f0, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Input = f0
	f1, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Output = f1
	f2, err := extWfType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Other = f2
	f3, err := EffectType().Decode(r)
	if err != nil {
		return v, err
	}
	v.Effect = f3
	return v, nil
}

// Effect is Lean's CapDAG.Effect: one of EffectUnspecified, EffectDeclared, EffectNone, EffectPatch.
type Effect interface{ isEffect() }

// EffectUnspecified is Lean's CapDAG.Effect.unspecified.
type EffectUnspecified struct{}

func (EffectUnspecified) isEffect() {}

// EffectDeclared is Lean's CapDAG.Effect.declared.
type EffectDeclared struct{}

func (EffectDeclared) isEffect() {}

// EffectNone is Lean's CapDAG.Effect.none.
type EffectNone struct{}

func (EffectNone) isEffect() {}

// EffectPatch is Lean's CapDAG.Effect.patch.
type EffectPatch struct{}

func (EffectPatch) isEffect() {}

// EffectFingerprint is the layout fingerprint of Lean's CapDAG.Effect: a package using Effect from this one checks it.
const EffectFingerprint = "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477"

type effectDescriptor struct{}

// EffectType describes CapDAG.Effect for polymorphic functions.
func EffectType() lungo.Type[Effect] {
	return effectDescriptor{}
}

func (t effectDescriptor) Expr() []byte { return lungo.InductiveExpr(1) }

func (t effectDescriptor) Encode(w *lungo.Writer, v Effect) error {
	switch x := v.(type) {
	case EffectUnspecified:
		w.U32(0)
		return nil
	case *EffectUnspecified:
		if x == nil {
			return lungo.Malformed("a nil *EffectUnspecified")
		}
		return t.Encode(w, *x)
	case EffectDeclared:
		w.U32(1)
		return nil
	case *EffectDeclared:
		if x == nil {
			return lungo.Malformed("a nil *EffectDeclared")
		}
		return t.Encode(w, *x)
	case EffectNone:
		w.U32(2)
		return nil
	case *EffectNone:
		if x == nil {
			return lungo.Malformed("a nil *EffectNone")
		}
		return t.Encode(w, *x)
	case EffectPatch:
		w.U32(3)
		return nil
	case *EffectPatch:
		if x == nil {
			return lungo.Malformed("a nil *EffectPatch")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Effect")
}

func (t effectDescriptor) Decode(r *lungo.Reader) (Effect, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v EffectUnspecified
		return v, nil
	case 1:
		var v EffectDeclared
		return v, nil
	case 2:
		var v EffectNone
		return v, nil
	case 3:
		var v EffectPatch
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of CapDAG.Effect", c)
}

// Constraint is Lean's TaggedUrn.Constraint: one of ConstraintMissing, ConstraintUnconstrained, ConstraintOptionalNot, ConstraintPresent, ConstraintPresentNot, ConstraintExact, ConstraintAbsent.
type Constraint interface{ isConstraint() }

// ConstraintMissing is Lean's TaggedUrn.Constraint.missing.
type ConstraintMissing struct{}

func (ConstraintMissing) isConstraint() {}

// ConstraintUnconstrained is Lean's TaggedUrn.Constraint.unconstrained.
type ConstraintUnconstrained struct{}

func (ConstraintUnconstrained) isConstraint() {}

// ConstraintOptionalNot is Lean's TaggedUrn.Constraint.optionalNot.
type ConstraintOptionalNot struct {
	Value string
}

func (ConstraintOptionalNot) isConstraint() {}

// ConstraintPresent is Lean's TaggedUrn.Constraint.present.
type ConstraintPresent struct{}

func (ConstraintPresent) isConstraint() {}

// ConstraintPresentNot is Lean's TaggedUrn.Constraint.presentNot.
type ConstraintPresentNot struct {
	Value string
}

func (ConstraintPresentNot) isConstraint() {}

// ConstraintExact is Lean's TaggedUrn.Constraint.exact.
type ConstraintExact struct {
	Value string
}

func (ConstraintExact) isConstraint() {}

// ConstraintAbsent is Lean's TaggedUrn.Constraint.absent.
type ConstraintAbsent struct{}

func (ConstraintAbsent) isConstraint() {}

// ConstraintFingerprint is the layout fingerprint of Lean's TaggedUrn.Constraint: a package using Constraint from this one checks it.
const ConstraintFingerprint = "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"

type constraintDescriptor struct{}

// ConstraintType describes TaggedUrn.Constraint for polymorphic functions.
func ConstraintType() lungo.Type[Constraint] {
	return constraintDescriptor{}
}

func (t constraintDescriptor) Expr() []byte { return lungo.InductiveExpr(2) }

func (t constraintDescriptor) Encode(w *lungo.Writer, v Constraint) error {
	switch x := v.(type) {
	case ConstraintMissing:
		w.U32(0)
		return nil
	case *ConstraintMissing:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintMissing")
		}
		return t.Encode(w, *x)
	case ConstraintUnconstrained:
		w.U32(1)
		return nil
	case *ConstraintUnconstrained:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintUnconstrained")
		}
		return t.Encode(w, *x)
	case ConstraintOptionalNot:
		w.U32(2)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintOptionalNot:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintOptionalNot")
		}
		return t.Encode(w, *x)
	case ConstraintPresent:
		w.U32(3)
		return nil
	case *ConstraintPresent:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintPresent")
		}
		return t.Encode(w, *x)
	case ConstraintPresentNot:
		w.U32(4)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintPresentNot:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintPresentNot")
		}
		return t.Encode(w, *x)
	case ConstraintExact:
		w.U32(5)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintExact:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintExact")
		}
		return t.Encode(w, *x)
	case ConstraintAbsent:
		w.U32(6)
		return nil
	case *ConstraintAbsent:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintAbsent")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Constraint")
}

func (t constraintDescriptor) Decode(r *lungo.Reader) (Constraint, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v ConstraintMissing
		return v, nil
	case 1:
		var v ConstraintUnconstrained
		return v, nil
	case 2:
		var v ConstraintOptionalNot
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 3:
		var v ConstraintPresent
		return v, nil
	case 4:
		var v ConstraintPresentNot
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 5:
		var v ConstraintExact
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 6:
		var v ConstraintAbsent
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of TaggedUrn.Constraint", c)
}

type extWfDescriptor struct{}

// extWfType describes Lean's TaggedUrn.Exec.Wf, provided by github.com/machinefabric/tagged-urn-go/formal.
func extWfType() lungo.Type[formal.Wf] {
	return extWfDescriptor{}
}

func (t extWfDescriptor) Expr() []byte { return lungo.InductiveExpr(3) }
func (t extWfDescriptor) Encode(w *lungo.Writer, v formal.Wf) error {
	return formal.WfType().Encode(w, v)
}
func (t extWfDescriptor) Decode(r *lungo.Reader) (formal.Wf, error) {
	return formal.WfType().Decode(r)
}

// Accepts is Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Accepts(pattern WfCap, request WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, pattern); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_daccepts), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Comparable is Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Comparable(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dcomparable), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Dispatch is Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Dispatch(candidate WfCap, request WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, candidate); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_ddispatch), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// EffectOk is Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool
func EffectOk(candidate Effect, request Effect) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = EffectType().Encode(w, candidate); err != nil {
		return
	}
	if err = EffectType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_deffectOk), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Equivalent is Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool
func Equivalent(a WfCap, b WfCap) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, a); err != nil {
		return
	}
	if err = WfCapType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dequivalent), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// RankingKey is Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat
func RankingKey(candidate WfCap, request WfCap) (result lungo.Pair[*big.Int, *big.Int], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, candidate); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_drankingKey), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.PairType(lungo.NatType, lungo.NatType))
}

// Select is Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap
func Select(candidates []WfCap, request WfCap) (result lungo.Option[WfCap], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.ListType(WfCapType()).Encode(w, candidates); err != nil {
		return
	}
	if err = WfCapType().Encode(w, request); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dselect), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(WfCapType()))
}

// Specificity is Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat
func Specificity(c_ WfCap) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfCapType().Encode(w, c_); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_CapDAG_dExec_dspecificity), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// Make is Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf
func Make(scheme string, tags []lungo.Pair[string, Constraint]) (result lungo.Option[formal.Wf], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.StringType.Encode(w, scheme); err != nil {
		return
	}
	if err = lungo.ListType(lungo.PairType(lungo.StringType, ConstraintType())).Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.capdagFormal__call_l_TaggedUrn_dExec_dmake), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(extWfType()))
}
